### ISSUE TITLE
0.5.0 release on pip

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#103]
Can we get the latest 0.5.0 release on pip? In pip it's still the old 0.4.5 https://pypi.org/project/cmake_format/. Many thanks.

**Comment by cheshirekow** [comment]
Woops. I guess I only pushed to `test.pypi.org`. I will push to the real one!

**Comment by cheshirekow** [comment]
Done!
https://pypi.org/project/cmake-format/
