### ISSUE TITLE
Extra space for export targets

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#104]
I am on the latest cmake-format, the below

```
export(TARGETS FILE ${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake)
```

will be formatted to 

```
export(TARGETS  FILE ${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake)
```

there are two spaces between `TARGETS` and `FILE`. Is there a way to make it one space?

**Comment by cheshirekow** [comment]
Note to self: the standard parser is emitting an empty positional argument as a child of the `KWARG`:
```
└─ BODY: 1:0
    └─ STATEMENT: 1:0
        ├─ FUNNAME: 1:0
        │   └─ Token(type=WORD, content='export', line=1, col=0)
        ├─ LPAREN: 1:6
        │   └─ Token(type=LEFT_PAREN, content='(', line=1, col=6)
        ├─ ARGGROUP: 1:7
        │   ├─ KWARGGROUP: 1:7
        │   │   ├─ KEYWORD: 1:7
        │   │   │   └─ Token(type=WORD, content='TARGETS', line=1, col=7)
        │   │   └─ PARGGROUP: 1:14
        │   │       └─ Token(type=WHITESPACE, content='  ', line=1, col=14) <--- here
        │   └─ KWARGGROUP: 1:16
        │       ├─ KEYWORD: 1:16
        │       │   └─ Token(type=WORD, content='FILE', line=1, col=16)
        │       └─ PARGGROUP: 1:20
        │           ├─ Token(type=WHITESPACE, content=' ', line=1, col=20)
        │           └─ ARGUMENT: 1:21
        │               └─ Token(type=UNQUOTED_LITERAL, content='${CMAKE_BINARY_DIR}/${CMAKE_PROJECT_NAME}Targets.cmake', line=1, col=21)
        └─ RPAREN: 1:75
            └─ Token(type=RIGHT_PAREN, content=')', line=1, col=75)
```

**Comment by cheshirekow** [comment]
I believe I have a fix for this. If you'd like to try yourself or need a quickfix you can check out the temporary `hotfixes_0.5.0` branch [here][1]

[1]: https://github.com/cheshirekow/cmake_format/tree/hotfixes_0.5.0

**Comment by jasjuang** [comment]
This might be a stupid question but how do I test it with the hot fix branch? There isn't a cmake-format.py or cmake-format executable somewhere in the repo.

**Comment by cheshirekow** [comment]
It's a fair question :wink: .

You have two easy options. 
1. In whatever python environment you are using you can use `pip install /path/to/cmake_format_clone`. This will essentially symlink the package into your python environment. This is will modify your python environment, replacing the package from `pypi.org`. 
2. You can export `PYTHONPATH=/path/to/cmake_format_clone` into your environment

In either case, run `python -Bm cmake_format` in place of `cmake-format`.

**Comment by jasjuang** [comment]
Thanks. I just verified that the hot fix branch fixes this problem!
