### ISSUE TITLE
Use same LICENSE as CMake?

### ISSUE THREAD

**Issue by tony** [cheshirekow/cmake_format#11]
If it's possible, can you make LICENSE permissive? (MIT/BSD/Apache, etc?)

Use the same LICENSE as CMake? https://cmake.org/licensing/

GPL causes conflicts with formatting plugins (since they are permissively licensed). GPL is only forward compatible with OSI licenses, not *backward* compatible. There are also tricky clauses in GPL that can become non-issues when a simpler license is used.

**Comment by cheshirekow** [comment]
Can you describe your particular problem? What do you by causing conflicts with formatting plugins?

**Comment by tony** [comment]
*I* do not have a problem. But plugin makers could, and they can't be counted on to participate in a protracted debate over licenses. This issue, is where your opinion for or against can be looked up. If for whatever reason, you insist on GPL, someone with a need for a permissive license formatter as to write their own, new one.

As I said previously, the current LICENSE at https://github.com/cheshirekow/cmake_format/blob/master/LICENSE isn't backward compatible. So MIT/BSD/Apache2/ISC/etc code, can't pull it in.

There is a tendency for people to have an issue with GPL, but they may not make an issue about it every time. I want to be careful. To my knowledge, nobody has implemented cmake_format *yet* as a plugin, but if someone were to consider, and LICENSE got in in their way, they can't be counted on to voice their opinion. They may opt to simply not invest the time creating a plugin that's incompatible with their own license.

This isn't about the behavior of any software, but the LICENSE not being compatible downstream in the future.

https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing

If a formatting library is permissively license, it can't implement this as a library and has to be careful about how it's used. Because GPL creatives a derivative in some circumstances.

In this project, cmake_format must be used in a certain way. With GPL, it must be access as a script, and cannot be imported, or have parts of it copied, without making the code that goes with it GPL too (which usually isn't desired).

**Comment by cheshirekow** [comment]
> In this project, cmake_format must be used in a certain way. With GPL, it must be accessed as a script via CLI or subprocess calls, but cannot be imported as a python module, or have parts of it copied, without making the code that goes with it GPL too (which usually isn't desired).

Seems fine to me. If anyone has an actual problem, I'm happy to discuss new licensing terms with them.

**Comment by jasjuang** [comment]
@tony I actually just made a [sublime plugin](https://github.com/jasjuang/sublime_cmake_format) out of this a few days ago... I intend to make this thing a free license. I am not well versed in the legalities, is this a problem with the current GPL license? 

@cheshirekow Are you okay with me making a sublime plugin out of this?

**Comment by tony** [comment]
@jasjuang how are you invoking it?  Via subprocess? If so, it could be OK

If you're using it via a library (e.g. ``import cmake_format``/``from cmake_format...``) there is an issue then

**Comment by jasjuang** [comment]
@tony Yes, it's a python script that invokes the `cmake-format` executable when certain conditions are met, so I guess this is fine?

**Comment by tony** [comment]
I presume so. (I am not a lawyer, though)

I think permissive license is safer, for all, still.

**Comment by cheshirekow** [comment]
@jasjung It's my understanding that calling `cmake-format` in a subprocess is allowed use under the license I've granted, so no problem.
