### ISSUE TITLE
Regression: 0.5.1 formats differently

### ISSUE THREAD

**Issue by kveretennicov** [cheshirekow/cmake_format#113]
```bash
$ cat test.txt 
cmake_policy(VERSION 3.11)

$ cat .cmake-format 
dangle_parens = False
max_subargs_per_line = 1
max_subpargs_per_line = 1
additional_commands = {
  "catkin_package": {
    "kwargs": {
      "INCLUDE_DIRS": "+",
      "LIBRARIES": "+",
      "CATKIN_DEPENDS": "+",
      "DEPENDS": "+"
    }
  },
  "target_add_coverage": {
    "kwargs": {
      "NAME": "+",
      "EXECUTABLE": "+",
      "EXECUTABLE_ARGS": "+",
      "DEPENDENCIES": "+"
    }
  },
  "set_test_properties": {
    "kwargs": {
      "PROPERTIES": "+",
      "LABELS": "+"
    }
  },
  "add_test": {
    "kwargs": {
      "NAME": "+",
      "COMMAND": "+"
    }
  }
}
always_wrap = ["catkin_package", "target_link_libraries", "target_include_directories", "target_add_coverage", "set_test_properties", "add_test", "install"]
```

With 0.4.5
```bash
$ cmake-format test.txt
cmake_policy(VERSION 3.11)
```

With 0.5.1
```bash
$ cmake-format test.txt
cmake_policy(VERSION
             3.11)
```

`find_package` formatting also became more "vertical" and arguably less natural.

The main point though is not specific details of formatting, but that we get different results for the same inputs+config. May I suggest that 0.5.x (or 0.6.x) is changed to produce the same outputs as 0.4.5.

**Comment by cheshirekow** [comment]
Until we get to a `1.0.0` release you can expect formatting to change from release to release. I know this is not ideal, but it is unavoidable at this stage of development. The next release will probably do away with `max_subargs_per_line`, but will hopefully add new knobs that allow for better fine-tuning of your formatting preferences. 

I'll note that with `max_subargs_per_line=1` I would expect every statement to be wrapped vertically as you are observing. With default configuration i see: 
```
cmake_policy(VERSION 3.11)
```
as you expect. You may want to go back to the default config and then tweak knobs to get the formatting you want.

**Comment by kveretennicov** [comment]
Fair enough and I appreciate the fact that it's 0.x software. We will be pinning cmake-format to 0.4.5 and will perhaps revisit it once 1.0 is out; tweaking the config knobs until 100+ cmake lists align doesn't seem very productive.

To avoid some user disappointment on your road to 1.0 you may want to embed expected software version into the config and fail loudly if it mismatches the running version. Cheers.
