### ISSUE TITLE
Example of adding custom cmake functions/macros to cmake-format configuration ?

### ISSUE THREAD

**Issue by aphecetche** [cheshirekow/cmake_format#114]
Would you have an example of how to make cmake_format recognize custom cmake functions ?

Let's say I have a custom function Foo that I use in a lot of my CMakeLists.txt  : 
```
Foo(somelib  OUTPUT foo.cxx HEADERS a.h b.h c.h LINKDEF fooLinkDef.h)
```

I'd like to have Foo highlighted as a function, and OUTPUT, HEADERS and LINKDEF as parameters. 
I assume this is possible, but how ?

Thanks

**Comment by aphecetche** [comment]
A follow-up on this one, as I think I more or less solved my initial problem.

Concerning getting cmake-format recognise (and thus format correctly) custom functions, this seems to work fine for me (and, ahem, ... it was in the doc... I should have seen it). 

```
# Specify structure for custom cmake functions
# * = ZERO_OR_MORE
# + = ONE_OR_MORE
additional_commands = {
    "add_root_dictionary": {
        "kwargs": {
            "LINKDEF": '+',
            "HEADERS": '*',
            "BASENAME": '*',
        }
    },
    "find_package_handle_standard_args": {
        "flags": ["CONFIG_MODE"],
        "kwargs": {
            "DEFAULT_MSG": '*',
            "REQUIRED_VARS": '*',
            "VERSION_VAR": '*',
            "HANDLE_COMPONENTS": '*',
            "FAIL_MESSAGE": '*'
        }
    }
}
```

(I'm not sure though if the * vs + are important ?) :  

Then, the highlighting I got from my editor, (Neo)vim. I was already using the syntax file from the [pboettch/vim-cmake-syntax](https://github.com/pboettch/vim-cmake-syntax) plugin. I just complemented it with the file below (that is put under `$HOME/..config/nvim/after/syntax/cmake.vim`) 

```
syn case ignore
syn keyword cmakeCommand
            \ find_package_handle_standard_args
            \ add_root_dictionary

syn case match

syn keyword cmakeKWadd_root_dictionary contained
            \ LINKDEF
            \ HEADERS
            \ BASENAME

syn keyword cmakeKWfind_package_handle_standard_args contained
            \ DEFAULT_MSG
            \ FOUND_VAR
            \ REQUIRED_VARS
            \ VERSION_VAR
            \ HANDLE_COMPONENTS
            \ CONFIG_MODE
            \ FAIL_MESSAGE

hi def link cmakeKWadd_root_dictionary ModeMsg
hi def link cmakeKWfind_package_handle_standard_args ModeMsg
```

**Comment by cheshirekow** [comment]
Great, I'm glad you found the examples. The "argument" of the map in custom command definitions is the "number of positional arguments consumed by the keyword". The special string `*` means "zero or more" and `+` means "one or more". These come into effect if, for example, you had a header file literally called `BASENAME`, and a call to your custom command like the following:

```
add_root_dictionary(HEADERS BASENAME foo bar BASENAME x y z)
```
The difference is whether or not that first `BASENAME` is grouped with `HEADERS`. The right hand side of the map can also be a specific numeric value like `1` (if the keyword takes a single value) or `2` if it takes exactly two values. 

Please leave this issue open as I would like to add more documentation on this feature to explain better how to use it.
