### ISSUE TITLE
execfile() was removed in Python 3

### ISSUE THREAD

**Issue by cclauss** [cheshirekow/cmake_format#12]
http://python-future.org/compatible_idioms.html#execfile

flake8 testing of https://github.com/cheshirekow/cmake_format on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./cmake_format/__main__.py:87:5: F821 undefined name 'execfile'
    execfile(configfile_path, config_dict)
    ^
./cmake_format/__main__.py:115:9: F821 undefined name 'execfile'
        execfile(configfile_path, config_dict)
        ^
2     F821 undefined name 'execfile'
```

**Comment by cheshirekow** [comment]
hm... that's a bummer. I guess `exec(open("./filename").read())` is recommended: https://stackoverflow.com/a/16577427

What's `flake8`?

**Comment by cclauss** [comment]
I like:
```python
with open("./filename") as in_file:
    exec(in_file.read())
```
because you don't know when the garbage collector will del the file handle and because the Python language spec does not guarantee that files left open will be closed when garbage collected.

* https://gitlab.com/pycqa/flake8
* http://flake8.pycqa.org

**Comment by cheshirekow** [comment]
too much reading... sounds like a linter. I use pylint for that. Anyway, how should I interpret the command like you posted?

**Comment by cclauss** [comment]
Use pylint but remember that it does not find __undefined names__ (F821 in flake8) so it won't find the two issues that I pointed out.

I will submit a PR.
