### ISSUE TITLE
auto-line ending option not working correctly under Windows

### ISSUE THREAD

**Issue by geieredgar** [cheshirekow/cmake_format#120]
When I run `cmake-format --line-ending auto -i CMakeLists.txt` under Windows, all `\r\n` characters are replaced by `\n`. I suspect this line to be the cause of it:
https://github.com/cheshirekow/cmake_format/blob/548b488f1aa0a246f6a1849243b6bc9f5f77646d/cmake_format/__main__.py#L450
Because of the missing newline argument, all newlines are automatically replaced by `\n`, even before the detect_line_endings function is called.
I created a PR containing the simple fix here: #119

**Comment by cheshirekow** [comment]
I guess the semantics of `newline=None` are different [than I had thought][1]. Looks like:

> When reading input from the stream, if newline is None, universal newlines mode is enabled. Lines in the input can end in '\n', '\r', or '\r\n', and these are translated into '\n' before being returned to the caller. If it is '', universal newlines mode is enabled, but line endings are returned to the caller untranslated. If it has any of the other legal values, input lines are only terminated by the given string, and the line ending is returned to the caller untranslated.

[1]: https://docs.python.org/3.5/library/functions.html#open

**Comment by cheshirekow** [comment]
Oh, I guess I realized this at some point before... it looks like `stdin` is opened with `newline=''` but the plain file is not.
