### ISSUE TITLE
Support `BYPRODUCTS` keyword for `add_custom_command`

### ISSUE THREAD

**Issue by d** [cheshirekow/cmake_format#121]
It was [added](https://cmake.org/cmake/help/v3.2/command/add_custom_command.html) in CMake 3.2 . It's frequently used when a project uses the Ninja generator because Ninja is quite particular about the exact "outcome" of each target / command.

I am willing to contribute, it seems I can fiddle with https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/parse_funs/add_xxx.py . But I'll need a few pointers about what the coding conventions are, how to run tests locally, and how I should add tests.

**Comment by cheshirekow** [comment]
Thanks for the suggestion. Certainly `cmake-format` should understand [it's own listfiles][3] ;). If you want to hack on it:

1. You found the right file to edit
2. Some [developer notes][1] in the README with how to run tests
3. You can add a test to [`add_custom_command_tests.py`][2]. It's a typical python `unittest`. You can just add a test function with `self.expect_format="""..."""` indicating the expected format. The base class will take care of the rest (don't worry about self.expect_parse in the existing test).

But it's also a pretty trivial change and I'm happy to just add it to the next incremental release. 

[1]: https://github.com/cheshirekow/cmake_format#developers
[2]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/command_tests/add_custom_command_tests.py 
[3]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/doc/CMakeLists.txt#L9
