### ISSUE TITLE
parse_positionals consumes non-related comments after code

### ISSUE THREAD

**Issue by volo-zyko** [cheshirekow/cmake_format#122]
I've encountered a problem with formatting of `ExternalProject_Add`.

Originally I manually formatted it as:

```cmake
ExternalProject_Add(
    FOO
    PREFIX              ${FOO_PREFIX}
    TMP_DIR             ${TMP_DIR}
    STAMP_DIR           ${FOO_PREFIX}/stamp
    # Download
    DOWNLOAD_DIR        ${DOWNLOAD_DIR}
    DOWNLOAD_NAME       ${FOO_ARCHIVE_FILE_NAME}
    URL                 ${STORAGE_URL}/${FOO_ARCHIVE_FILE_NAME}
    URL_MD5             ${FOO_MD5}
    # Patch
    PATCH_COMMAND       ${PATCH_COMMAND} ${PROJECT_SOURCE_DIR}/patch.diff
    # Configure
    SOURCE_DIR          ${SRC_DIR}
    CMAKE_ARGS          ${CMAKE_OPTS}
    # Build
    BUILD_IN_SOURCE     1
    BUILD_BYPRODUCTS    ${CUR_COMPONENT_ARTIFACTS}
    # Logging
    LOG_CONFIGURE       1
    LOG_BUILD           1
    LOG_INSTALL         1
)
```

cmake-format changed the formatting to the following:

```cmake
ExternalProject_Add(FOO
                    PREFIX ${FOO_PREFIX}
                    TMP_DIR ${TMP_DIR}
                    STAMP_DIR ${FOO_PREFIX}/stamp
                    # Download
                    DOWNLOAD_DIR ${DOWNLOAD_DIR}
                    DOWNLOAD_NAME ${FOO_ARCHIVE_FILE_NAME}
                    URL ${STORAGE_URL}/${FOO_ARCHIVE_FILE_NAME}
                    URL_MD5 ${FOO_MD5}
                    # Patch
                    PATCH_COMMAND ${PATCH_COMMAND} ${PROJECT_SOURCE_DIR}/patch.diff
                                  # Configure
                    SOURCE_DIR ${SRC_DIR}
                    CMAKE_ARGS ${CMAKE_OPTS}
                               # Build
                    BUILD_IN_SOURCE 1
                    BUILD_BYPRODUCTS ${CUR_COMPONENT_ARTIFACTS}
                                     # Logging
                    LOG_CONFIGURE 1
                    LOG_BUILD 1
                    LOG_INSTALL 1)
```

The new formatting in general is fine except for those ugly comments. The culprit is `parse_positionals` in `parser.py` which consumes everything after `PATCH_COMMAND` and till `SOURCE_DIR` (it behaves similarly for the other 2 cases). Now I'm thinking about how to fix it. I came up with a heuristics that comments are normally placed before the related code or after it but on the same line, i.e. if the comment is on a separate line after the code then it's not related to that code, hence `cmake-format` should handle it separately. This certainly should apply only if `npargs in ('+', '*')`. Also, this behavior can be managed by a config option. So, before sending a pull request I wanted to hear opinions whether it makes any sense.

**Comment by cheshirekow** [comment]
> comments are normally placed before the related code or after it but on the same line, i.e. if the comment is on a separate line after the code then it's not related to that code,

This is actually what is currently implemented. 

The problem is actually one of scope comprehension. `PATCH_COMMAND`  consumes an arbitrary number of positional arguments and `cmake-format` doesn't "look-ahead" (yet) to know when the argument list of this keyword is complete. It consumes arguments as positional arguments of `PATCH_COMMAND` up to the next keyword `SOURCE_DIR`. It knows that `# Configure` is a line comment, but it believes it to be within the scope of the `PATCH_COMMAND` argument list. In a way, `cmake-format` thinks that there *might* be another `PATCH_COMMAND` positional argument following the comment, in which case the current formatting would in fact be appropriate. 

This doesn't present an issue for `STAMP_DIR` or `URL_MD5` because `cmake-format` knows that these keywords only take exactly one argument each. Therefore it breaks out of the "scope" of those keywords after consuming a single token, and then associates the subsequent comment with the active argument list (which is the main argument list).

The correct way to resolve this issue (which is already in the works) is to [look *past* the comment][1], and inspect the next non-comment argument token when deciding whether or not to "break" the current nesting level (scope). 

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/parser.py#L375

**Comment by cheshirekow** [comment]
Also, note to self: this is a great example of when #36 would really help readability.

**Comment by volo-zyko** [comment]
> The correct way to resolve this issue (which is already in the works) is to look past the comment, and inspect the next non-comment argument token when deciding whether or not to "break" the current nesting level (scope).

Either way it's still a heuristics.

While I was trying to fix the issue by changing `parse_positionals` I discovered that I broke several tests which can be divided to 2 cases.

1. I changed the formatting from:
```cmake
target_link_libraries(libraryname
                      PUBLIC ${COMMON_LIBRARIES}
                             # add more library dependencies here
                      )
```
to 
```cmake
target_link_libraries(libraryname
                      PUBLIC ${COMMON_LIBRARIES}
                      # add more library dependencies here
                      )
```

2. I changed:
```cmake
find_package(package REQUIRED
             COMPONENTS # --------------------------------------
                        # @TODO: This has to be filled manually
                        # --------------------------------------
                        this_is_a_really_long_word_foo)
```
to
```cmake
find_package(package REQUIRED
             COMPONENTS # --------------------------------------
             # @TODO: This has to be filled manually
             # --------------------------------------
             this_is_a_really_long_word_foo)
```

These 2 are not equivalent. While in the case 2 this really looks like a broken formatting, the case 1 is not so obviously broken. In other words, it's hard to guess what the comment is about and to which block it should be aligned. So, why not refuse the temptation to guess and not make it more formal? Say, comments between rulers should be equally aligned. Or, if one needs a multi-line comment after some code a bracket comment can be employed. This will require some changes in the user code but also will make the format tuning more flexible. What do you think?

**Comment by cheshirekow** [comment]
>  In other words, it's hard to guess what the comment is about and to which block it should be aligned.

I somewhat disagree. I don't think it's too hard to infer the intent. If the existing comment is aligned to a semantic element prior to formatting, than I think that's a good hint of where it should be aligned after formatting. In your case I think it's not so hard for cmake-format to look at the the arguments before and after the comment and understand what are valid columns for a line-comment (associated with a particular argument list). If the comment is already in a column that matches a semantic depth, then associate the comment with that argument list and keep it aligned in the output. Specifically, I think it is quite possible for `cmake-format` to retain either of:

```
target_link_libraries(libraryname
                      PUBLIC ${COMMON_LIBRARIES}
                      # add more library dependencies here
                      )
```
or
```
target_link_libraries(libraryname
                      PUBLIC ${COMMON_LIBRARIES}
                             # add more library dependencies here
                      )
```
If the comment doesn't align to either column, then default to the outer-most one. 

Your suggestion of requiring something special for argument comments is reasonable. I have considered something like doxygen-style trailing comments, and require a `<` such that 

```
argument_foo #< this comment is associated
             #< with the preceeding argument
```

but I'm not convinced it's necessary and I'd prefer to keep things as lightweight as possible. Let's see if my intended fix for your issue doesn't fit the bill and then we can talk about enabling a more-explicit syntax for argument-matching comments.

**Comment by volo-zyko** [comment]
Ok, let's see and I like the idea of `#<` comments.

**Comment by cheshirekow** [comment]
This is halfway implemented. The parser now inspects the column of each line comment and will group them accordingly. The next step is to walk up the tree and find the correct node to associate with.

**Comment by cheshirekow** [comment]
This is done. Comments are preserved at the semantic depth they are parsed out. There is also an optional `#<` syntax for explicit trailing comments. There is a test similar to your example so hopefully your situation is well addressed. Please let me know if you see otherwise.

**Comment by volo-zyko** [comment]
Thanks a lot. I checked it works.
