### ISSUE TITLE
Issue with .*\ parsing for regexes

### ISSUE THREAD

**Issue by StableCoder** [cheshirekow/cmake_format#127]
There's a bit of an issue where sometimes cmake-format will reformat some valid regex items, specifically in this case the `.*\` at the beginning of a line.

For example, from:
```
add_code_coverage_all_targets(EXCLUDE
                              /usr/*
                              .*\.test\..*
                              .*/test/.*
                              .*/tests/.*
                              .*/external/.*
                              *test*)

list(FILTER
     CL_FILES
     EXCLUDE
     REGEX
     .*\.vert\.hpp)
```

to this:
```
add_code_coverage_all_targets(EXCLUDE
                              /usr/*
                              .*
                              \.test\..*
                              .*/test/.*
                              .*/tests/.*
                              .*/external/.*
                              *test*)

list(FILTER
     CL_FILES
     EXCLUDE
     REGEX
     .*
     \.vert\.hpp)
```

Not quite the most optimal, as those were still fully valid regex strings. It's not too big of a deal, but still a minor annoyance.

**Comment by StableCoder** [comment]
Yeah, quotes do work, thanks.

**Comment by cheshirekow** [comment]
Yeah, this is similar to #107. It appears that backslash in an unquoted argument is illegal according to the [cmake documentation][2]. I guess that the cmake implementation is more generous than the documentation indicates. 

[2]: https://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#unquoted-argument

**Comment by cheshirekow** [comment]
I'm going to close this as "not-a-bug" since it appears the lexing logic matches what is *documented* for cmake (versus what is implemented). If you would like to discuss further though please feel free to reply and if this causes serious problems for anyone we can revisit.
