### ISSUE TITLE
cmakeFormat.args in settings.json yields Incorrect type

### ISSUE THREAD

**Issue by hugolm84** [cheshirekow/cmake_format#129]
Hi!

Trying to use the vs code extension and get type error when configuring extra args.

![image](https://user-images.githubusercontent.com/867096/65054839-83a88480-d96e-11e9-8dd6-d51d81b16357.png)

Using as stated in the example: 
```
{
    "cmakeFormat.args": ["--config-file", "../.cmake-format.py"]
}
```

vscode: cmake-format 0.42

python:
pip install cmake_format
Requirement already satisfied: cmake_format in c:\users\hlindst\appdata\local\programs\python\python37\lib\site-packages (0.4.5)

What am I doing wrong? Cheers :)

**Comment by cheshirekow** [comment]
Hm... That looks right to me. Let me see if I can reproduce.
