### ISSUE TITLE
Wrong formatting of install(TARGETS) commands

### ISSUE THREAD

**Issue by GianUlli** [cheshirekow/cmake_format#134]
I ran `cmake-format` 0.5.5 on a file with a lot of `install` commands. It messed up with `install(TARGETS ...)`:

    install(TARGETS target
        CONFIGURATIONS Debug
        RUNTIME DESTINATION Debug/bin)

(Example from the CMake documentation: https://cmake.org/cmake/help/v3.16/command/install.html)

The tool seems to classify `CONFIGURATIONS` as a further target.

`install(FILES ...)` commands work as expected:

    install(FILES foo.h
                  bar.h
            CONFIGURATIONS Debug
                           Release
            DESTINATION include)

**Comment by GianUlli** [comment]
I can fix the issue if I add `"CONFIGURATIONS": PositionalParser('+')` as a new kwarg in `parse_install_targets`. However, I'm not sure how this affects other target-type-specific (?) `CONFIGURATION` commands (e.g. `RUNTIME CONFIGURATION Debug`), which are also valid CMake. The CMake documentation on this is confusing me.

**Comment by cheshirekow** [comment]
Hm... I guess I didn't realize you could leave off the `ARCHIVE`, `LIBRARY`, etc bit. The problem doesn't appear specific to `CONFIGURATIONS`, it will most likely be present for any of `DESTINATION`, `PERMISSIONS`, `COMPONENT`, and `NAMELINK_COMPONENT` used outside of the `ARCHIVE`, `LIBRARY`, etc. Should be relatively easy to correct.

**Comment by cheshirekow** [comment]
Should be fixed in `v0.6.2` currently live on pypi. There is [a test][1].

[1]: https://github.com/cheshirekow/cmake_format/blob/v0.6.2/cmake_format/command_tests/install_tests.cmake
