### ISSUE TITLE
Custom command -- add USES_TERMINAL to kwargs

### ISSUE THREAD

**Issue by amerlyq** [cheshirekow/cmake_format#140]
Before and After:
```cmake
add_custom_target(run_${PROJECT_NAME}
  COMMAND ${_cmd}
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  USES_TERMINAL
  VERBATIM
)

add_custom_target(
  run_${PROJECT_NAME}
  COMMAND ${_cmd}
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} USES_TERMINAL
  VERBATIM
)
```
P.S. here also I can't agree on wrapping 1st argument -- it's *special* enough to be left on same line as function. Maybe we need option to make such behavior consistent ? For ones who love 1st argument wrapping and for those who don't. In any case we will have bunch of exceptions from the rule :(

**Comment by cheshirekow** [comment]
:+1: on `USES_TERMINAL`. 
See the discussion in #137 regarding first argument.

**Comment by cheshirekow** [comment]
[Added][1] in `v0.6.2`. 

[1]: https://github.com/cheshirekow/cmake_format/blob/v0.6.2/cmake_format/parse_funs/add_xxx.py
