### ISSUE TITLE
Add a --check option that doesn't write the files and just returns whether the files would have been formatted

### ISSUE THREAD

**Issue by pwalch** [cheshirekow/cmake_format#142]
In the Black formatter in Python, there is a `--check` option with the following description:
> Don't write the files back, just return the status. Return code 0 means nothing would change. Return code 1 means some files would be reformatted.

This option is particularly useful to enforce the formatter rules in a CI job without wrapping the call into some bash code to diff the files.

**Comment by pwalch** [comment]
Hi @cheshirekow! This issue follows our discussion on Discord the other day. Thanks for having an amazing response time of 3 minutes :clap:

**Comment by cheshirekow** [comment]
Added in `v0.6.2`.
