### ISSUE TITLE
Broken file attributes after formatting

### ISSUE THREAD

**Issue by Hsilgos** [cheshirekow/cmake_format#143]
Some of our *.cmake files have +x mod (i.e. they are executable) and after applying of cmake-format they are not executable anymore.

Steps:

1. Create file test.cmake
2. Write something which requires formatting.
3. > chmod +x test.cmake
4. > cmake-format -i test.cmake

Result:
test.cmake is not executable

Expected:
test.cmake is executable

**Comment by cheshirekow** [comment]
`cmake-format` doesn't write out over the file it is formatting. It writes to a temp file next to the output file, and then copies over the output file. This way if formatting fails you don't have a corrupt file.

It doesn't currently copy file attributes but that would be easy to add. I'll include it in the next push.

**Comment by cheshirekow** [comment]
Added in `v0.6.2`.
