### ISSUE TITLE
Wrong warning about "file (TOUCH_NOCREATE ...)"

### ISSUE THREAD

**Issue by Hsilgos** [cheshirekow/cmake_format#144]
Steps to reproduce:

1. Create cmake file with with next cmake instruction: file (TOUCH_NOCREATE "some/path")
2. Apply cmake-format

Result:
Warning
> [WARNING] file.py:405: Invalid file() form "TOUCH_NOCREATE" at ...

Expected result: No warning

Note:
There is seems bug in [file.py](https://github.com/cheshirekow/cmake_format/blob/2a4d453f2391e7b648db255993165533d1f6ce58/cmake_format/parse_funs/file.py) which looks for keyword TOUCH_NO_CREATE, not TOUCH_NOCREATE

**Comment by cheshirekow** [comment]
Fixed in `v0.6.2`
