### ISSUE TITLE
Bad formating for `set_target_properties` function

### ISSUE THREAD

**Issue by mrdimfox** [cheshirekow/cmake_format#145]
If I have a function call like this
```cmake
set_target_properties(
    ${PROJECT_NAME}
    PROPERTIES C_STANDARD 11
               C_STANDARD_REQUIRED YES
               C_EXTENSIONS YES
               CXX_STANDARD 17
               CXX_STANDARD_REQUIRED YES
               CXX_EXTENSIONS YES
               COMPILE_FLAGS -Wunused
)
```
it will be formatted like this
```cmake
set_target_properties(
    ${PROJECT_NAME}_hw
    PROPERTIES C_STANDARD
               11
               C_STANDARD_REQUIRED
               YES
               C_EXTENSIONS
               YES
               CXX_STANDARD
               17
               CXX_STANDARD_REQUIRED
               YES
               CXX_EXTENSIONS
               YES
               COMPILE_FLAGS
               -Wunused
)
```

I think it's a wrong format, isn't it? Also, it can be fixed by
```python
    "set_target_properties": {
        "kwargs": {
            "PROPERTIES": {
                "kwargs": {
                    "C_STANDARD": 1,
                    "C_STANDARD_REQUIRED": 1,
                    "C_EXTENSIONS": 1,
                    "CXX_STANDARD": 1,
                    "CXX_STANDARD_REQUIRED": 1,
                    "CXX_EXTENSIONS": 1,
                    "COMPILE_FLAGS": "1",
                }
            }
        }
    },
```
But should not it works out of the box for one of the standard cmake function?

cmake-format version: 0.6.0 (same version of VS Code extension).

**Comment by mrdimfox** [comment]
There are [a lot of properties](https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#target-properties) and nobody can cover all of them in a config-file. I think, it is definitely should be a special case in the code.

**Comment by cheshirekow** [comment]
> I think, it is definitely should be a special case in the code.
Agreed.

**Comment by mrdimfox** [comment]
@cheshirekow Cool! Thanks.

**Comment by cheshirekow** [comment]
Ok actually this is solved in a different way than "known variables". The `set_target_properties` command takes pairs of values, so I switched the parser to the "tuple" parser, which knows about "pairs" and the [formatting is improved][1]

[1]: https://github.com/cheshirekow/cmake_format/blob/v0.6.2/cmake_format/command_tests/set_target_properties_tests.cmake
