### ISSUE TITLE
cmake-lint: Human redable errors

### ISSUE THREAD

**Issue by sergeyklay** [cheshirekow/cmake_format#154]
Is there any possibility to not throw stack trace in case of any error? IMO would be better to show human readable error message instead of python code.
```
$ cmake-lint ./cmake/
Traceback (most recent call last):
  File "~/.venv/local/bin/cmake-lint", line 8, in <module>
    sys.exit(main())
  File "~/.venv/local/lib/python3.7/site-packages/cmake_lint/__main__.py", line 128, in main
    infile_path, 'r', encoding=cfg.input_encoding, newline='')
IsADirectoryError: [Errno 21] Is a directory: './cmake/'
```

**Comment by cheshirekow** [comment]
`cmake-lint` doesn't intentionally dump. Can you provide some context to help debug? What command did you run?

**Comment by sergeyklay** [comment]
I ran `cmake-lint ./cmake/` (the same as for `cmake-lint ./cmake/*.cmake`)

**Comment by sergeyklay** [comment]
I just wanted to share my point of view - showing something like "hey man, you have pass a file path, not directory" is more professional than stacktrace as above ^ :man_shrugging:

**Comment by cheshirekow** [comment]
Yeah sure, I'll add an error message. The stack trace isn't intentional. I hadn't considered the case that someone would try to use a directory as an input file.

**Comment by cheshirekow** [comment]
Error messages were updated in `v0.6.5`
