### ISSUE TITLE
How to apply customized config file

### ISSUE THREAD

**Issue by SE-June** [cheshirekow/cmake_format#155]
Hi!

When my customized file was applied to vscode, I got the following error:

" Command failed: cmake-format --config-file d:\totalcmd\util\VSCode-win32-x64-1.38.1 - Traceback (most recent call last): File "C:\Python27\Scripts\cmake-format-script.py", line 11, in <module> load_entry_point('cmake-format==0.6.4', 'console_scripts', 'cmake-format')() File "c:\python27\lib\site-packages\cmake_format\__main__.py", line 472, in main "You cannot mix stdin as an input with other input files" AssertionError: You cannot mix stdin as an input with other input files"

my settings.json
     "cmakeFormat.args": [
        "--config-file d:\\totalcmd\\util\\VSCode-win32-x64-1.38.1"
    ],

my setting.json is attached.

Merry Christmas!

[settings.json.txt](https://github.com/cheshirekow/cmake_format/files/3997245/settings.json.txt)

**Comment by cheshirekow** [comment]
I think the problem is that you need to separate the two command line arguments, like this:

```
"cmakeFormat.args": [
   "--config-file", "d:\totalcmd\util\VSCode-win32-x64-1.38.1"
]
```
Otherwise it is interpreted all as a single argument string. Give that a try and let me know how it goes.

**Comment by SE-June** [comment]
I have captured how cmake-format.ext was called using "Procmon.exe" of "SysinternalsSuite"

The following config(which is suggested), **_"cmakeFormat.args": [  "--config-file", "d:\totalcmd\util\VSCode-win32-x64-1.38.1" ]_**
 made a call to "cmake-format.exe" as followings:
   **_cmake-format --config-file "d:	otalcmdtilSCode-win32-x64-1.38.1" -_**
I thouht backslash,"\" is used to escape a following character but not used for path delimiter.



So I changed  "\" to '/' as followings
   **_"cmakeFormat.args": [ "--config-file", "d:/totalcmd/util/VSCode-win32-x64-1.38.1" ]_**

and then I got the two followings sequences :
 **_cmake-format --config-file d:/totalcmd/util/VSCode-win32-x64-1.38.1 -
 c:\python27\python.exe "C:\Python27\Scripts\cmake-format-script.py" "--config-file" "d:/totalcmd/util/VSCode-win32-x64-1.38.1" "-"_**



But Both didn't work.

After doing formating in both cases, my cmake files was empty( All was deleted )

**Comment by cheshirekow** [comment]
Oh I see. Thank you for digging in further and providing the additional information. It looks like vscode itself is interpreting these backslashes as escape sequences. This is news to me. I wont have access to a windows machine for the next couple of days to reproduce this issue, but I will try myself when I can. 

In the meantime, I suggest trying to escape the backslash itself by using *double* backslash:

```
"cmakeFormat.args": [ "--config-file", "d:\\totalcmd\\util\\VSCode-win32-x64-1.38.1" ]
```

**Comment by SE-June** [comment]
Also I changed "\" to "\\" like the followings:
"cmakeFormat.args": [ "--config-file", "d:\\totalcmd\\util\\\VSCode-win32-x64-1.38.1" ]
in that case, I got the two following sequences.
cmake-format --config-file d:\totalcmd\util\VSCode-win32-x64-1.38.1 -
c:\python27\python.exe "C:\Python27\Scripts\cmake-format-script.py" "--config-file" "d:\totalcmd\util\VSCode-win32-x64-1.38.1" "-"

It also didn't work

**Comment by cheshirekow** [comment]
Can you clarify what didn't work in this case? Did you see an error message? I'm not familiar with the `cmake-format-script.py` part but I suspect that is perhaps something that `setuptools` does on windows. On linux, it is different. If my suspicion is correct, then that command line looks right. 

> what is the last symbol, "-" for?

Positional arguments are the names of files to format. `-` means format `stdin`.  It is automatically appended because the visual studio code extension pipes the file content to the `cmake-format` subprocess over `stdin`.

**Comment by SE-June** [comment]
After doing formatting in every cases, my cmake files was empty( All was deleted )

**Comment by cheshirekow** [comment]
> After doing formatting in every cases, my cmake files was empty

Hm... that's not good. Even if `cmake-format` itself is crashing the extension shouldn't replace the content of your listfiles. It looks like indeed the status of the [subprocess command is not checked by the extension][1]. I've filed this as bug #05489cf. That makes debugging more difficult, but is not the cause of your problem.

My hypothesis is that something in your configuration is causing `cmake-format` to error out. Can you share the content of your config file `VSCode-win32-x64-1.38.1`? 

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/vscode_extension/src/extension.ts#L73

**Comment by SE-June** [comment]
Here is my two config file which I tried to use

The original name is "cmake-format.config" 
To upload it, I changed it to "cmake-format.config.txt"
[cmake-format.config.txt](https://github.com/cheshirekow/cmake_format/files/4001319/cmake-format.config.txt)

The original name is ".cmake-format.py" 
To upload it, I changed it to "_.cmake-format.py.txt"
[_.cmake-format.py.txt](https://github.com/cheshirekow/cmake_format/files/4001321/_.cmake-format.py.txt)

**Comment by cheshirekow** [comment]
Ah! If you wish to use the `--config-file` command line option, you should specify the full path to the file `d:\totalcmd\util\VSCode-win32-x64-1.38.1\.cmake-format.py`. 

`cmake-format` doesn't understand `ini` style configuration files, just JSON, YAML, or python so I recommend using a `.json`, `.yml` or `.py` file extension to make it clear to `cmake-format` what style config file you are using. 

If you specify the `--config-file` command line option, `cmake-format` will use that config file, and it can have any filename that you want (though please use the correct file extension, otherwise `cmake-format` will try to infer the correct style). You don't have to name it `.cmake-format.py`. You could name it `my-cmake-format-config.py` or similar. 

That sounds like it is likely the problem. Sorry that the error is getting chomped and is not visible. Give that a try and let me know how it goes.

**Comment by SE-June** [comment]
I tried with the following setting.
  "cmakeFormat.args": [ "--config-file", "d:\\totalcmd\\util\\VSCode-win32-x64-1.38.1\\.cmake-format.py" ]

But It still didn't work.

All contents was deleted

**Comment by cheshirekow** [comment]
Can you try the same with the double backslash?
```
"cmakeFormat.args": [ "--config-file", "d:\\totalcmd\\util\\VSCode-win32-x64-1.38.1\\.cmake-format.py" ]
```
But if that doesn't work, I will report back after I can reproduce on my windows machine. 

Happy near year also.

**Comment by SE-June** [comment]
"cmakeFormat.args": [
        "--config-file",
        "d:\\\\totalcmd\\util\\\\VSCode-win32-x64-1.38.1\\\\.cmake-format.py"
    ]

It still didn't work

All contents was deleted

**Comment by cheshirekow** [comment]
Try this:
```
"cmakeFormat.args": [
    "--config-file",
    "d:\\totalcmd\\util\\VSCode-win32-x64-1.38.1\\.cmake-format.py",
    "--"
]
```
I forgot that `--config-file` can take multiple arguments, so if it's the last argument on the command line it needs to be separated from positional arguments. This works for me on windows using your python style config file.

**Comment by SE-June** [comment]
Thank you so much.
It also worked for me!!!!

Thanks again for making this great tool!!!

**Comment by cheshirekow** [comment]
I've created #4e6ca84 to "Insert `--` after `--config-file` if needed" automatically in the extension to hopefully avoid this problem for other users, as well as #6551ce1 "exit with nonzero status if no input files" to make this failure case more discoverable.
