### ISSUE TITLE
No handler for logger, error in Circle CI

### ISSUE THREAD

**Issue by kumaran-14** [cheshirekow/cmake_format#157]
```No handlers could be found for logger "cmake_format.__main__"
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 499, in main
    outtext, reflow_valid = process_file(cfg, intext, args.dump)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 122, in process_file
    parse_tree = parse.parse(tokens, ctx)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parse/__init__.py", line 41, in parse
    return BodyNode.consume(ctx, tokens)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/parse/body_nodes.py", line 70, in consume
    tokens[0].begin.line, tokens[0].begin.col))
AssertionError: Unexpected UNQUOTED_LITERAL token at 76:0
No handlers could be found for logger "cmake-format"
No handlers could be found for logger "cmake-format"
No handlers could be found for logger "cmake-format"
No handlers could be found for logger "cmake-format"
```
Environment: Docker image is bionic ubuntu.

Any cmake-format command in circleci config is taking too much time to complete.
Please look into this.

**Comment by cheshirekow** [comment]
So, what's the issue here? 
* 1. The stack trace you posted?
* 2. the amount of time to take?
* 3. the message in the title?

Please provide an example input file, your config file, and let me know what version of `cmake-format` and python you are using.

**Comment by kumaran-14** [comment]
I use this script to check file formatting. This script is executed in circleci config.
```
find . \( -path './ext' -o -path './build' -o -path './simulator' \) -prune -o -type f \( -iname '*.cmake' -o -iname 'CMakeLists.txt' \) -exec cmake-format -i {} \; || { echo "cmake-format run failed;" exit 1; } 
```

I use this to install cmake-format
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&  python get-pip.py && pip install cmake-format
```

**Comment by kumaran-14** [comment]
```
Successfully installed cmake-format-0.6.5
Python 2.7.17
```
The command ```cmake-format``` takes close to 4 minutes to complete.

**Comment by cheshirekow** [comment]
> The command cmake-format takes close to 4 minutes to complete.

If that is what you mean, based on the shell command you provided above, it looks like you call `cmake-format` once per listfile. Can you provide me with the listfile that takes 4 minutes?

If you *actually* mean "The above shell command takes close to 4 minutes to complete", then how many listfiles are you processing? How many files are returned by:

```
find . \( -path './ext' -o -path './build' -o -path './simulator' \) -prune -o -type f \( -iname '*.cmake' -o -iname 'CMakeLists.txt' \) 
```

**Comment by kumaran-14** [comment]
Can confirm that its taking 4 mins for around 6 files.

**Comment by cheshirekow** [comment]
Ok that's helpful information. Please check how long is being spent on each file. If most of the time is one one file, please share that file so I can try to reproduce the issue. If the amount of time spent on each file is similar, please share any one of them.

**Comment by kumaran-14** [comment]
It takes about the same time for only one file.  
For example, this file : ```clang-format.cmake```
```
# Creates additional target to perform clang-format run, requires clang-format
# Find clang format
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR})
find_package(ClangFormat)

if(CLANG_FORMAT_FOUND)
  message("** Found clang-format")
  message("** clang-format executable location: ${CLANG_FORMAT_EXECUTABLE}")
  message("** clang-format version: ${CLANG_FORMAT_VERSION}")
else()
  message(SEND_ERROR "clang-format executable not found")
endif()

# Get all project files
file(
  GLOB_RECURSE
  ALL_SOURCE_FILES
  src/*.cpp
  src/*.h
  src/*.hpp
  src/*.proto
  test/*.cpp
  test/*.h)

# Add target to build
add_custom_target(clangformat COMMAND ${CLANG_FORMAT_EXECUTABLE} -style=file -i
                                      ${ALL_SOURCE_FILES})
```

**Comment by cheshirekow** [comment]
Interesting. I'm seeing approximately 50ms to process that file on my three bionic machines with python version 2.7.15. Two questions:

* Where are you installing python `2.7.17` from? 
* Can you paste the environment (output of `env`) that cmake-format is running in?

And two suggestions:

1. Try with the default python 2.7 installed in bionic, or with the python 3
2. Try without the `-i`. This is not what you want, but I'm curious if there is some issue with the write speed of the storage backend.

**Comment by kumaran-14** [comment]
@cheshirekow Its strange. The docker container equivalent to circleci config runs fine. It formats properly and does not take much time.
```
# Base image
FROM buildpack-deps:bionic

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&  python get-pip.py && pip install cmake-format

COPY ./clang-format.cmake /root/

RUN echo $(python --version)

RUN echo $(cmake-format --version)

RUN echo $(env)

RUN cat /root/clang-format.cmake

RUN cmake-format -i /root/clang-format.cmake

RUN cat /root/clang-format.cmake
```
Even in this way it executes without much time.  1-2 secs. 
```

version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    enviroment:
      CXX: "clang++-8"
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&  python get-pip.py && pip install cmake-format
            echo $(python --version)
            echo $(cmake-format --version)
            echo "#####################"
            echo $(env)
            echo "######################"
      - run:
          working_directory: /root/project/
          command: |
            echo "#####################"
            cat ./clang-format.cmake
            echo "#####################"
            cmake-format -i ./clang-format.cmake
            echo "#####################"
            cat ./clang-format.cmake
            echo "#####################"
            cat ./CMakeLists.txt
            echo "####################"
            cmake-format ./CMakeLists.txt
            echo "#####################"
            cat ./CMakeLists.txt
            echo "#####################"
```
How did you clone the error in your system?

**Comment by cheshirekow** [comment]
> The docker container equivalent to circleci config runs fine.

I don't think that's equivalent. Looking at the source for [buildpack-deps:bionic][1] (and it's dependencies), I would expect `echo $(python version)` to be `2.7.15`, not `2.7.17`. Can you upload the output of that docker test? 

> How did you clone the error in your system?

I did not reproduce the error on my system. As I said, it only takes about 50ms on my machines. 

Also, please answer the two questions from my comment above, and if you can please try my two suggestions and let me know what happens.

**Comment by kumaran-14** [comment]
The dockerfile output:
```
Python 2.7.17
0.6.5
HOSTNAME=9ea65f91ac43 HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PWD=/
```
The ```cat``` commands produce output as expected.
First is unformatted file output, next is correct formatted output.

I'm not installing python, it comes with the base image.
I tried it without -i flag. My circleci config is mentioned above, where I dont use the -i flag. It runs quicker.

**Comment by kumaran-14** [comment]
Top most error log before the traceback log:
```No handlers could be found for logger "cmake-format"
No handlers could be found for logger "cmake_format.__main__"
```

**Comment by cheshirekow** [comment]
> I'm not installing python, it comes with the base image.

I see. I just traced through the docker containers. It looks like it comes in at the `builddeps-scm` image. Digging in a bit further, this appears to be a recent update (Nov 7th 2019) in the bionic upstream. I've upgraded my python version and things look fine with `2.7.17`. 

> I tried it without -i flag. My circleci config is mentioned above, where I dont use the -i flag. It runs quicker.

How much quicker? Like "problem solved" quicker? That would seem to suggest that there is a problem writing data to the source tree in your builders. i.e. sounds like a circleci issue. What is the storage backend of your builders? Does `checkout` clone to a physical device (SSD) or are the files sourced from network storage?

The *warning* messages (note: these are not errors) about "No handlers could be found" are unusual. It means that the python logging system is not initialized. But that is done [here][1], which makes me think there is something unusual about the environment. 

In any case, that is unlikely to be related to the long runtime, which is probably caused by something else. 

[1]: https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/__main__.py#L548

**Comment by kumaran-14** [comment]
@cheshirekow Found the issue. The reason for time consumption is because the script I use takes a lot more files that I thought it did.
I originally thought that only 6 files exist, but I curl and build some stuff, which also gets included.
However, the logger not found issue does not come up for these 6 files, but arise on few of the unintended files. I do not know what causes these errors. 
Its a mistake on my part. I apologize for consuming your time.

**Comment by cheshirekow** [comment]
Gotcha, thanks for letting me know the resolution.
