### ISSUE TITLE
Incorrect example on the release page

### ISSUE THREAD

**Issue by sergeyklay** [cheshirekow/cmake_format#158]
[Release page](https://github.com/cheshirekow/cmake_format/releases/tag/v0.6.6) says:

> `cmake-format` can update your configuration file for you with the following command:
```
cmake-format --config-file <your-config> --dump-config <your-format> \
    --no-help --no-defaults
```

Actual behavior:
```bash
$ cmake-format --config-file .cmake-format --dump-config yaml --no-help --no-defaults
usage: 
cmake-format [-h]
             [--dump-config {yaml,json,python} | -i | -o OUTFILE_PATH]
             [-c CONFIG_FILE]
             infilepath [infilepath ...]
cmake-format: error: unrecognized arguments: --no-defaults
```

Also it's unclear to me what is `config_files`:
```bash
$ cmake-format --config-file .cmake-format --dump-config yaml --no-help | head -n 1
WARNING config_util.py:299: The following configuration options were ignored:
  config_files
```

I have no `config_files` section / keyword

**Comment by cheshirekow** [comment]
Use `--no-default` (typo in the release notes, drop the `s`)

> Also it's unclear to me what is config_files

This is probably a bug. I think the command line `config_files` is leaking into the configuration object initialization. You can safely ignore the warning.

**Comment by sergeyklay** [comment]
Thank you for so quick response

**Comment by cheshirekow** [comment]
The release page has been updated so I'm going to close this. The spurious warning will be fixed in the next version too.

**Comment by sergeyklay** [comment]
Thank you
