### ISSUE TITLE
Config uses only default values

### ISSUE THREAD

**Issue by DanielChabrowski** [cheshirekow/cmake_format#16]
Hey. I noticed that updated config has only default values.

get_config returns a dict with `tab_size` = 10
after `config_dict.update(vars(args))` it's 2 (default value)

Therefore it's only using default values, no matter what I put in the config file. Same goes for other parameters.

Python 2.7.14

**Comment by cheshirekow** [comment]
Thanks for reporting the issue, and thanks for taking the time to track down the problem location!
