### ISSUE TITLE
Clean up CMake build script

### ISSUE THREAD

**Issue by Martchus** [cheshirekow/cmake_format#160]
It is apparently possible to run the test suite using CMake/CTest. However, I'm really wondering about all the dependencies stated in CMakeLists.txt. Does this project really need gnuradio libraries and vulkan? It looks like you've just copied the CMakeLists.txt from a template. Maybe it is time to clean it up?

**Comment by Martchus** [comment]
By the way, it also seems that one of the test fails. I'm not sure whether these tests are supposed to be run by packager or are for development only but that's the error I'm getting:

```
======================================================================
FAIL: test_all_commands_in_db (__main__.TestCommandDatabase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/cmake-format/src/cmake_format-0.6.7/cmake_format/test/command_db_test.py", line 38, in test_all_commands_in_db
    self.assertFalse(bool(missing_commands), msg=message)
AssertionError: True is not false : Missing commands:
  add_link_options
  target_link_directories
  target_link_options
  target_precompile_headers

----------------------------------------------------------------------
Ran 1 test in 0.288s

FAILED (failures=1)
```

**Comment by cheshirekow** [comment]
This project is exported from a much larger mono-repo. I have plans for distributing the dependency declarations closer to where they are used, but that is low priority. The pkg find stuff in the root cmake is advisory. The cmake-format build system will run just fine without these packages installed. 

The test which is failing for you executes cmake and compares the list of available commands to those that `cmake-format` has definitions for. It is failing for you because you have a newer version of cmake than I do on my workstations and in CI.

**Comment by Martchus** [comment]
Ok, that explains it. And yes, beside some warnings there's no harm in having CMake to look for that dependencies.

The explanation about the failing test makes sense as well. I simply excluded it from my build for now. I also had to exclude `cmake_format-validate-database` for Tumbleweed packaging because it requires an internet connection for some gpg stuff.

**Comment by cheshirekow** [comment]
> also had to exclude cmake_format-validate-database 

That should be fine. The purpose of this test is to validate pull requests on github. There are 4 tests of this nature. The other three actually skip themselves if they are not a travis pull-request built. It might be a good idea to enable a "no-network" build option in the cmake to disable such tests. I'll add a note.

>  for Tumbleweed packaging

For packaging purposes, you might prefer to use the [wheel from pypi.org][1]

[1]: https://pypi.org/project/cmake-format/#files

**Comment by Martchus** [comment]
But I don't prefer to use the "wheel" (crazy alias for archive?) from pypi. The reason is that it doesn't contain the CMakeLists.txt which is useful for running tests.

**Comment by cheshirekow** [comment]
Fair enough.
