### ISSUE TITLE
Reconsider hard version requirements

### ISSUE THREAD

**Issue by Martchus** [cheshirekow/cmake_format#161]
Wouldn't it make more sense to specify `six>=1.14.0` (instead of `six==1.14.0`) in `setup.py`? Likely newer versions of this Python module work as well. Otherwise it is hard to distribute that project for GNU/Linux. The same counts for the other dependencies in `setup.py`.

**Comment by cheshirekow** [comment]
This has already been done. Look for it in the next release.

**Comment by Martchus** [comment]
I can not find such a change on any of the publicly visible branches. The relevant file is https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/pypi/setup.py, right?

**Comment by cheshirekow** [comment]
It's not pushed yet, look for it in the next release.

**Comment by Martchus** [comment]
Ok, thanks for taking care. And thanks for the project - you seem to put a lot of effort into it and it is appreciated.

**Comment by cheshirekow** [comment]
You're welcome :slightly_smiling_face:
