### ISSUE TITLE
Internal error on very first (and last) invocation.

### ISSUE THREAD

**Issue by CarloWood** [cheshirekow/cmake_format#164]
sean:~/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite>cmake-format CMakeLists.txt
WARNING __main__.py:490: While processing CMakeLists.txt
ERROR __main__.py:549: An internal error occured. Please consider filing a bug report at github.com/cheshirekow/cmake_format/issues
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 540, in main
    return inner_main()
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 484, in inner_main
    outtext, reflow_valid = process_file(cfg, intext, args.dump)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 131, in process_file
    box_tree = formatter.layout_tree(parse_tree, config)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 1590, in layout_tree
    root_box.reflow(stack_context, Cursor(0, 0))
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 465, in reflow
    stack_context, cursor.clone(), passno)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 1409, in _reflow
    cursor = child.reflow(stack_context, column_cursor, passno)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 706, in reflow
    max(passno for passno, _ in self._layout_passes))
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 465, in reflow
    stack_context, cursor.clone(), passno)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/formatter.py", line 785, in _reflow
    .format(child.node_type, child.pnode))
AssertionError: Expected ARGGROUP node, but got NodeType.PARGGROUP at PARGGROUP: 31:28

I'd argue that the most serious bug here is that it doesn't even say where in the CMakeLists.txt it was when this problem occurred... This is hard to debug for me (I don't know phyton).

**Comment by CarloWood** [comment]
Well, did a "binary search" and it crashes on this line:

FetchContent_MakeAvailable( ${hg_name} )

Also when I change the argument. Apparently on just seeing `FetchContent_MakeAvailable`. Really strange, why would it crash on calling a function/macro ?!

**Comment by cheshirekow** [comment]
> I'd argue that the most serious bug here is that it doesn't even say where in the CMakeLists.txt it was when this problem occurred... This is hard to debug for me (I don't know phyton).

```
AssertionError: Expected ARGGROUP node, but got NodeType.PARGGROUP at PARGGROUP: 31:28
                                                                                 ^^^^^                                                            
```
Line 38, column 28.

In any case, I'm able to reproduce and will look into it.

**Comment by cheshirekow** [comment]
Fix appears to be this, and will be included in the next push:
```
diff --git a/cmake_format/parse_funs/fetch_content.py b/cmake_format/parse_funs/fetch_content.py
index d4a0b35..0390660 100644
--- a/cmake_format/parse_funs/fetch_content.py
+++ b/cmake_format/parse_funs/fetch_content.py
@@ -1,6 +1,6 @@
 from cmake_format.parse.additional_nodes import ShellCommandNode
 from cmake_format.parse.argument_nodes import (
-    PositionalParser, StandardArgTree)
+    PositionalParser, StandardArgTree, StandardParser)
 
 
 def parse_fetchcontent_declare(ctx, tokens, breakstack):
@@ -159,4 +159,4 @@ def populate_db(parse_db):
   parse_db["fetchcontent_declare"] = parse_fetchcontent_declare
   parse_db["fetchcontent_populate"] = parse_fetchcontent_populate
   parse_db["fetchcontent_getproperties"] = parse_fetchcontent_getproperties
-  parse_db["fetchcontent_makeavailable"] = PositionalParser('+')
+  parse_db["fetchcontent_makeavailable"] = StandardParser('+')

```
