### ISSUE TITLE
Fails to dump config file...

### ISSUE THREAD

**Issue by CarloWood** [cheshirekow/cmake_format#165]
sean:~/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite>cmake-format --dump-config json > cmake-format.json
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 540, in main
    return inner_main()
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 437, in inner_main
    config_dict = get_config(os.getcwd(), args.config_files)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 296, in get_config
    return get_configdict(configfile_paths)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 250, in get_configdict
    increment_dict = get_one_config_dict(configfile_path)
  File "/usr/local/lib/python2.7/dist-packages/cmake_format/__main__.py", line 232, in get_one_config_dict
    return json.load(config_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by cheshirekow** [comment]
Hi, 

Based on the location of the error, I think you might have a broken config file in the search path of the working directory where you are running from. Try `cmake-format --dump-config json` from a clean location (e.g. `/tmp` or `/`) and let me know if you continue to have this problem.

The problematic configuration is probably named `cmake-format.json` or `.cmake-format.json` in one of these directories:

* /home
* /home/sean
* /home/sean/projects
* /home/sean/projects/aicxx
* /home/sean/projects/aicxx/ai-statefulstask-testsuite
* /home/sean/projects/aicxx/ai-statefulstask-testsuite/ai-statefulstask-testsuite

And based on the error message the problem is that it is empty. Once you locate it, try editing it to be an empty JSON object (`{}`).

**Comment by cheshirekow** [comment]
I've added what is hopefully a more helpful error message to help identify cases like this.

**Comment by cheshirekow** [comment]
Did you find the offending config file? Did you manage to dump the config OK?

**Comment by CarloWood** [comment]
No sorry, I had deleted it. The first time it dumped ok. I can't recall what happened after that (a crash I think). Trying to dump it after that again that crashed too. I didn't know the content of the output file would matter when generating a dump file... Anyway, in an empty directory I can dump a json file, but I can't tell you under what circumstances that stopped working, anymore.

**Comment by CarloWood** [comment]
I see you marked it as not-a-bug -- not sure about that. All I did was run cmake-format commands; if that gets itself in a non-consistent state where it can't even dump a config file anymore then that seems a bug to me :p.

**Comment by cheshirekow** [comment]
>  I didn't know the content of the output file would matter when generating a dump file..

`cmake-format` will [automatically search for a config file][1] to support immediate and inherent configuration for a particular project. For example, if you clone a project and edit a file, when you run `cmake-format` on it, it will automatically use that project's configuration (if it exists). 

`--dump-config` will load config files in the search path and then dump the resolved configuration. This is for two reasons:

1. To help you debug "why is this file formatting in this way I do not expect... what is the configuration used for this file?"
2. To help you update your existing config files when options change

> I see you marked it as not-a-bug -- not sure about that.

Well, there's nothing actionable in this thread yet so...

>  The first time it dumped ok. I can't recall what happened after that (a crash I think).
> ...
>  All I did was run cmake-format commands;

In that case here is my hypothesis. I suspect you ran `cmake-format --dump-config > .cmake-format.json`. Note that the default format for `--dump-config` is not json, so you dump non-json to a JSON config file. The next time you ran `--dump-config` it choked on loading the file. 

Regardless, if you're unable to reproduce the problem and you are currently not experiencing this problem, then I'll close the bug. Feel free to post additional comments if you have more information to share or encounter the issue again. 

I did add an error message to `v0.6.8` that will tell you which config file failed to parse if it fails to parse a config, which will hopefully helpout anyone else that ends up where you did. 

[1]: https://cmake-format.readthedocs.io/en/latest/configuration.html

**Comment by CarloWood** [comment]
Hi,

the command that I ran is in my first post, at the top, although it got broken up. It was:

    $ cmake-format --dump-config json > cmake-format.json

Hence, I did specify 'json' but I picked (at random) the exact same file name as it is trying to read.
The above command creates an empty file (for writing) before starting cmake-format, which subsequently chokes on trying to read that empty file.

What went wrong here is that I was not aware that cmake-format was reading by default a config file when dumping the config, much less that that file (among others) is called `cmake-format.json` in the current directory. This information is not in the output of `cmake-format --help`. If I missed it by not reading a manual or FAQ then I apologize.

**Comment by cheshirekow** [comment]
I see, that makes sense. 
The list of patterns matched for automatic config files is listed in the [documentation][1]. I'll add a bit to skip parsing an empty JSON file to ease users through this edge case. 

[1] https://cmake-format.readthedocs.io/en/latest/configuration.html
