### ISSUE TITLE
Does not install(?)

### ISSUE THREAD

**Issue by CarloWood** [cheshirekow/cmake_format#167]
I had deleted cmake_format, but after your kind replies I tried to reinstall it.

The only instructions for doing so seem to be at the top of the README.rst file that says I have to run `pip install cmake_format`

Doing so resulted in,

> sean:/usr/src/cmake_format/cmake_format>pip install cmake_format
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support 
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: cmake_format in /usr/local/lib/python2.7/dist-packages (0.6.7)
> Requirement already satisfied: six==1.14.0 in /usr/local/lib/python2.7/dist-packages (from cmake_format) (1.14.0)

So that seemed to have done nothing. After that there was no cmake-format (or cmake_format) to be found anywhere. Not in my PATH nor in the source tree.

I tried then also running 'make', 'cmake' and 'setup.py', but none of those resulted in anything useful.

Please explain how to (re)install this :/

**Comment by cheshirekow** [comment]
This will depend entirely on how your system is configured. Your `pip` says:
```
Requirement already satisfied: cmake_format in /usr/local/lib/python2.7/dist-packages (0.6.7)
```
So:

1. Is `cmake-format` in `/usr/local/bin`?
2. is `/usr/local/bin` on your `PATH`? 
3. How did you uninstall it? Did you use `pip uninstall` or did you did you delete it manually?

**Comment by CarloWood** [comment]
1. It was, but I deleted it from there when I deleted it.
2. Yes
3. I deleted (using 'rm') what I could find. But since I have no clue whatsoever what pip is or about python, I'm sure I didn't do it the 'correct' way :/

**Comment by cheshirekow** [comment]
In that case I think you've left your pip index in an inconsistent state. You've deleted pip-managed files without deleting their metadata. For future reference, use `pip uninstall` to delete a pip-managed package. It's equivalent to using `apt remove make` versus deleting `/usr/bin/make`.

In your case, I suspect that the following will fix you up: `pip install --force-reinstall cmake-format`.

**Comment by CarloWood** [comment]
Thank you that worked.

Before closing this issue, can you explain how I can install cmake-format from the git clone? The source tree that I cloned contains a `CMakeLists.txt` and already a `Makefile` (huh?) as well as a `setup.py`. If I use `pip` then I'm not really using the git repository at all right? So what commands are needed to install without pip, from the git source tree?

**Comment by cheshirekow** [comment]
You can install from the clone using pip:
```
$ git clone https://github.com/cheshirekow/cmake_format.git
$ pip install cmake_format/
```

**Comment by cheshirekow** [comment]
Please let me know if that worked for you and if we can close this issue.

**Comment by cheshirekow** [comment]
I haven't heard anything in a week so I'm going to close this issue. Feel free to add another comment if you are still having trouble though.
