### ISSUE TITLE
Crash when running `cmake-lint --dump-config`

### ISSUE THREAD

**Issue by mortenfyhn** [cheshirekow/cmake_format#171]
Hi, I just installed `cmake-format`. I found out about it via the C++ Weekly channel on youtube, and it looks really nice.

I'm getting a possible bug:

When running `cmake-lint --dump-config`, the program crashes: 

![cmakelint](https://user-images.githubusercontent.com/6639836/76213789-b9d30c80-620b-11ea-854d-de8296766f49.png)

**Comment by cheshirekow** [comment]
Oops. In the meantime, `cmake-format --dump-config` will do the same thing (they are in fact the same codepath, and the two programs use the same config file).

**Comment by mortenfyhn** [comment]
Cool, thanks!

**Comment by cescobaz** [comment]
Hello, config dump is still crashing on my machine. What ever format I ask, yaml, json, python or empty, always the same result:
<img width="969" alt="Screenshot 2022-09-30 at 13 48 04" src="https://user-images.githubusercontent.com/1547072/193263543-af3052c6-853b-4320-b673-ae1cf062c9f8.png">

Command: `cmake-format --dump-config yaml`
cmake-format version: `0.6.13`

**Comment by cescobaz** [comment]
Sorry guys, my fault: I installed with `pip3` so I tried to re-install with `pip` and everything works!
