### ISSUE TITLE
Possibly false positives for too many newlines [C0305]

### ISSUE THREAD

**Issue by mortenfyhn** [cheshirekow/cmake_format#172]
With a minimal CMakeLists.txt file, I'm getting errors when running `cmake-lint` if there are newlines at all. As I interpret it, "max statement spacing" of 1 would mean that I'm allowed one blank line between statements, but no more. Does it actually mean zero?

Here's what I get, with the minimal example CMake file. I need to set max statement spacing to 2 to allow one blank line between statements:

![spacing](https://user-images.githubusercontent.com/6639836/76214472-1a167e00-620d-11ea-935d-df6d8da36c37.png)

**Comment by cheshirekow** [comment]
I think it's actually the required number of `newline` characters ([see here][1]). So if you want a blank line, I think it should be two. Incidentally, it looks like the default is `1` which is probably wrong. I think I meant for it to be two by default.  

P.S. `cmake-lint` is very very new. There's likely to be a few bugs here and there. But it does have [some pretty cool checkers][2] implemented already. 

[1]: https://cmake-format.readthedocs.io/en/latest/configopts.html#max-statement-spacing
[2]: https://cmake-format.readthedocs.io/en/latest/lint-summary.html

**Comment by mortenfyhn** [comment]
Yeah, that also makes sense. I interpreted it as number of empty lines, not newline characters. 2 as the default sounds good.

I'm interested in using this in CI to check CMake formatting. Would you recommend sticking to `cmake-format --check` instead of `cmake-lint` for the time being? As far as I understand they do similar things, but `cmake-format --check` tells if there are formatting errors or not, without specifying which ones.

**Comment by cheshirekow** [comment]
I would recommend sticking to `cmake-format --check` for now. The two are actually quite different. `cmake-format --check` will check for formatting errors (actually it just checks to see if `cmake-format` would change anything). `cmake-lint` does do some simple formatting checks, but also does static analysis to look for common pitfalls and readability problems. I would suggest waiting to use `cmake-lint` in CI until it is at least used in CI for this project itself. At that point it should have at least enough coverage that I would feel comfortable recommending it as a merge gate.

**Comment by mortenfyhn** [comment]
I see! I didn't realize the difference before. Thank you! I'll stick to `cmake-format --check` for now.
