### ISSUE TITLE
Formatting support for find_package_handle_standard_args()

### ISSUE THREAD

**Issue by moha-gh** [cheshirekow/cmake_format#173]
We have a number of custom [Find Modules](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) that make use of [FindPackageHandleStandardArgs](https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html). As cmake-format however does not seem to provide a formatting configuration for `find_package_handle_standard_args()` out of the box, the formatting is off. So instead of

```
find_package_handle_standard_args(
    CustomLib
    REQUIRED_VARS
        CUSTOM_LIB_1
        CUSTOM_LIB_2
        CUSTOM_LIB_INCLUDE_BASE_DIR
)
```

you get something like this:

```
find_package_handle_standard_args(
    CustomLib
    REQUIRED_VARS
    CUSTOM_LIB_1
    CUSTOM_LIB_2
    CUSTOM_LIB_INCLUDE_BASE_DIR
)
```

As `find_package_handle_standard_args()` is widely used, I'd be great if support could be added. I'd be happy to support with testing, if required. In case I get a few pointers on how to implement this (new module in  `cmake_format/parse_funs/`?) and how to best deal with the two different signatures that `find_package_handle_standard_args()` offers, I could also put my limited Python skills to use and (try to) provide a draft PR.

**Comment by cheshirekow** [comment]
I have intentionally held off on this for the time being. Instead, I have focused my effort on trying to *programmatically generate* the command specifications for standard modules. I started by trying to parse the output of (e.g.) `cmake --help-module FindPackageHandleStandardArgs`. In this case: 

```
   find_package_handle_standard_args(<PackageName>
     (DEFAULT_MSG|<custom-failure-message>)
     <required-var>...
     )

   find_package_handle_standard_args(<PackageName>
     [FOUND_VAR <result-var>]
     [REQUIRED_VARS <required-var>...]
     [VERSION_VAR <version-var>]
     [HANDLE_COMPONENTS]
     [CONFIG_MODE]
     [FAIL_MESSAGE <custom-failure-message>]
     )
```

But what I found is that actually the cmake documentation is quite inconsistent with how these docstrings are written (they must not be generated from source). 

My current planned approach, is to parse the module itself with `cmake-genparsers` (introduced in [v0.6.7][1]). For example:
```
cmake-genparsers /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake
```
will output: 
```
{ 'find_package_handle_standard_args': 
  { 'kwargs': { 'FAIL_MESSAGE': 1,
              'FOUND_VAR': 1,
              'REQUIRED_VARS': '+',
              'VERSION_VAR': 1},
  'pargs': { 'flags': [ 'CONFIG_MODE',
                        'HANDLE_COMPONENTS'],
            'nargs': '2+'}}
}
```
which can be used directly [in the config ][2]. 

`cmake-genparsers` in the current release is unfortunately a little broken (the above output is from the dev branch). 

So, if you can wait a little longer, I am planning in the next release to include generated specifications for all of the build in modules available at build time. My hope is that this covers about 90% of the standard distribution module commands. The remaining 10% will require some hand coding. `find_package_handle_standard_args` in particular has two forms and will require a custom parser to discriminate between them. 

[1]: https://cmake-format.readthedocs.io/en/latest/release_notes.html#v0-6-7
[2]: https://cmake-format.readthedocs.io/en/latest/configopts.html#additional-commands

**Comment by moha-gh** [comment]
> So, if you can wait a little longer, I am planning in the next release to include generated specifications for all of the build in modules available at build time.

Great, that'd be fine. We'll just wait for the next release then :+1:
