### ISSUE TITLE
line break in url

### ISSUE THREAD

**Issue by AlexanderLanin** [cheshirekow/cmake_format#182]
Usually cmake-format will not add line breaks into urls.
However given an url with a '-' sign within a comment, it is being split:

This one is fine:

    set(libb2_url
        https://github.com/BLAKE2/libb2/releases/download/v${libb2_version}/libb2-${libb2_version}.tar.gz
    )

This one is not:

    # Compare: https://repology.org/badge/vertical-allrepos/cmake.svg?minversion=3.4.3

With:

    line_width: 80

---
Expected:

    # Compare:
    # https://repology.org/badge/vertical-allrepos/cmake.svg?minversion=3.4.3

Actual:

    # Compare: https://repology.org/badge/vertical
    # -allrepos/cmake.svg?minversion=3.4.3

**Comment by cheshirekow** [comment]
Within a comment, different rules apply. The text is wrapped using python's textwrap module, which I think views the dash as a potential word break. You can wrap your url with a literal fence to prevent wrapping:

```
# Compare:
# ~~~
# https://repology.org/badge/vertical-allrepos/cmake.svg?minversion=3.4.3
# ~~~
```

Or you can use a bracket comment:

```
#[[Compare: https://repology.org/badge/vertical-allrepos/cmake.svg?minversion=3.4.3]]
```

**Comment by AlexanderLanin** [comment]
Yeah I ended up with ~~~ for the moment. Trouble is that the url is clickable even within comments and wrong if it's wrapped.
If it were not clickable wrapping would be fine. But since some/most/all editors allow clicking on urls wrapping seems wrong even within comments.

**Comment by cheshirekow** [comment]
Preserving things like URLs is a reasonable request. I think at the very least exposing some of the text wrap configuration options would be worthwhile such as [break_long_words][1] or [break_on_hyphen][2]. I think it would be a good idea to change both of those to `false` by default though. 

[1]: https://docs.python.org/3/library/textwrap.html#textwrap.TextWrapper.break_long_words
[2]: https://docs.python.org/3/library/textwrap.html#textwrap.TextWrapper.break_on_hyphens
