### ISSUE TITLE
Trailing whitespace reported on wrong line

### ISSUE THREAD

**Issue by AlexanderLanin** [cheshirekow/cmake_format#184]
Given:

    # this line is fine, the next is not.
    # whitespace here: 

(That is line 1 and 2. Line 2 ends with a space)

Output:

    cmake/GenerateVersionFile.cmake:01: [C0303] Trailing whitespace

Version: 0.6.9

**Comment by cheshirekow** [comment]
```
# this line is fine, the next is not.  <-- this is line 0
# whitespace here:                     <-- this is line 1
```

**Comment by AlexanderLanin** [comment]
No that's not right. Because when I click on any other warning the editor jumps to the right line. In case of C0303 it jumps one line too high.

**Comment by cheshirekow** [comment]
Oh, well then, I'll look into that.

**Comment by AlexanderLanin** [comment]
_Could_ be related to whether the line number has a column number.

    # This one is fine.
    # This should trigger line too long warning...........................................
    # Trailing whitespace: 
    set(x ON)
    option(ENABLE_CPPCHECK "Enable static analysis with cppcheck ...................." OFF)

Results in:

    cmake/CodeAnalysis.cmake:01: [C0301] Line too long (86/80)
    cmake/CodeAnalysis.cmake:02: [C0303] Trailing whitespace
    cmake/CodeAnalysis.cmake:04: [C0301] Line too long (87/80)
    cmake/CodeAnalysis.cmake:04,04: [C0103] Invalid directory variable name "x"

I would recommend starting to count at line 1 as that's where GUIs jump when someone clicks on `cmake/CodeAnalysis.cmake:02`

**Comment by cheshirekow** [comment]
Ok it seems the line numbers as assigned by the tokenizer start with "1", whereas the basic checker is starting from "0". I'll make it so that they start from "1" consistently.
