### ISSUE TITLE
Keep line breaks in comments

### ISSUE THREAD

**Issue by okainov** [cheshirekow/cmake_format#194]
I have this in my cmake file:

```
# * Try to find libusb-1.0
# Once done this will define
#
# LIBUSB_1_FOUND - system has libusb
# LIBUSB_1_INCLUDE_DIRS - the libusb include directory
# LIBUSB_1_LIBRARIES - Link these to use libusb
# LIBUSB_1_DEFINITIONS - Compiler switches required for using libusb
```
What cmake-format does is 
```
# * Try to find libusb-1.0 Once done this will define
#
# LIBUSB_1_FOUND - system has libusb LIBUSB_1_INCLUDE_DIRS - the libusb include
# directory LIBUSB_1_LIBRARIES - Link these to use libusb LIBUSB_1_DEFINITIONS -
# Compiler switches required for using libusb
```

Is there a way to keep the newlines in comments for some blocks? The reformatting feature is useful for normal multi-line text comments, but it doesn't work well when line breaks are intentional. And adding more extra new lines  just as separator between single list entries looks very ugly, that's not an option :(

**Comment by cheshirekow** [comment]
You have two options:

1. use a literal fence
2. format it as a list

See the [markup documentation][1] for information about these options.

[1]: https://cmake-format.readthedocs.io/en/latest/format-features.html#markup

**Comment by okainov** [comment]
Thanks, I think list formatting worked well here
