### ISSUE TITLE
Cmake-lint:  [C0103] Invalid CACHE variable 

### ISSUE THREAD

**Issue by okainov** [cheshirekow/cmake_format#197]
Cmake-lint complains:
> cmake/gtest.cmake:16,06: [C0103] Invalid CACHE variable name "gtest_force_shared_crt" doesn't match `[A-Z][0-9A-Z_]+`

Extract of my cmake:
```
  set(gtest_force_shared_crt
      ON
      CACHE BOOL "See googletest/googletest/CMakeLists.txt")
```

I'm not really getting the problem, `gtest_force_shared_crt` is the name that we use as per official readme https://github.com/google/googletest/blob/master/googletest/README.md, should it be fixed in cmake-lint or can I ignore it somehow?

**Comment by cheshirekow** [comment]
By default the rule is to use [all-caps snake-case][4] for any global (CACHE or non-internal directory) variables. You have three options:

1. If your project uses a different convention everywhere, then [change the pattern][1]
2. If the rule is not meaningful to your project, then [disable the rule][2]
3. If this is a one-off exception, then locally disable the hit with `#cmake-format: disable=` (see e.g. the [example][3]). 

Note that option (3) currently can only be applied at "block level", for the duration of the current scope. Meaning any subsequent `set()` in the same scope will also have this check disabled. There is not yet an implementation of "disable next" or "disable this line"

[1]: https://cmake-format.readthedocs.io/en/latest/configopts.html#global-var-pattern
[2]: https://cmake-format.readthedocs.io/en/latest/configopts.html#disabled-codes
[3]: https://cmake-format.readthedocs.io/en/latest/lint-example.html
[4]: https://cmake-format.readthedocs.io/en/latest/lint-notes.html#variable-naming-conventions

**Comment by cheshirekow** [comment]
On second read, I realize that you are setting a cache variable which is actually used by a third party cmake module. In this case I recommend option (3) above. Ideally you would be able to locally disable it only once, but that is not yet possible (soon though).
