### ISSUE TITLE
What is "upstream"?

### ISSUE THREAD

**Issue by rpavlik** [cheshirekow/cmake_format#200]
When looking at old pull requests to try to figure out maintenance, etc. practices (and why so many requests were just closed without merge, and each commit is a massive monolithic change corresponding to a release) - I noticed this: https://github.com/cheshirekow/cmake_format/pull/149#issuecomment-555339584

"But don't sweat it, I've pulled your typo fixes in upstream and I'll include them in the next push."

Is there some other repository that is "upstream" that changes should be submitted to? Or is this mostly an internal project made source-available, with github as a release system?

I really like this functionality - works better than my personal, earlier attempt to do something similar (in a much less complete way) and would like to participate, but I'm confused by the signs whether the sorts of "drive-by contributions" I typically start with are desired.

**Comment by cheshirekow** [comment]
> Or is this mostly an internal project made source-available, with github as a release system?

This one. Though "source-available" usually means something different than how you're using it, and github is more for issue tracking than release. pypi is for release. 

>  "drive-by contributions" I typically start with are desired.

Meaningful contributions are definitely welcome.

**Comment by rpavlik** [comment]
Thanks for clarification! The git history had me confused.
