### ISSUE TITLE
Usage: banning tabs and enforcing the spaces per tab

### ISSUE THREAD

**Issue by tylerjereddy** [cheshirekow/cmake_format#210]
This may simply be a usage question rather than a feature request, or maybe it is out of scope for the library, but I don't seem to be able to get the linter to complain about:

1) tabs being present at the start of lines instead of spaces (setting `tab_size = 4` doesn't actually seem to prohibit tabs and enforce the usage of spaces at the start of lines?)
2) Even if I replace all the tabs with spaces, the linter still doesn't seem to complain if `tab_size = 2`, but my CMake code is formatted with `4` spaces for example. I'm not sure how thoroughly this can be enforced since whitespace generally doesn't have meaning for CMake, and so the indentation logic/AST-style parsing might get messy pretty fast.

So, am I just missing some incantation flags for the linter (or something in the config file) to actually complain about tabs vs. spaces and X spaces vs Y spaces for logical indents?

I ended up writing my own Python module to scrape through files and complain if a tab was present, but I'm wondering if I can avoid an in-house solution and use `cmake_format` before I commit to that route.

**Comment by cheshirekow** [comment]
I don't think I have [anything implemented][1] for whitespace consistency in `cmake-lint`, however there is a separate `cmake-format --check` [which will exit ][2] with an error if the formatting doesn't match. It's a bit of a hammer, as you might not want to check *all* the formatting, but that is what we have so far. 

I think tab-policy is a very reasonable `cmake-lint` request though. 

[1]: https://cmake-format.readthedocs.io/en/latest/lint-summary.html
[2]: https://cmake-format.readthedocs.io/en/latest/format-usage.html

**Comment by tylerjereddy** [comment]
Can I mass-disable all format options except for `tab_size` so that `--check` only exits with an error code if it violates the single specific formatting issue I care about?

Also, will the whitespace checking follow nested logic for +2, +4, and so on for nested conditionals and so on? I imagine this is a little tricky.

**Comment by cheshirekow** [comment]
> Can I mass-disable all format options except for tab_size so that --check only exits with an error code if it violates the single specific formatting issue I care about?

Unfortunately not. The design of `cmake-format` is such that there really isn't an "on/off" for individual aspects of the formatting. It's kind of all or nothing. You can tweak knobs of the algorithm used to do the formatting, but I don't think you can accomplish "just adjust whitespace" with `cmake-format`. 

> Also, will the whitespace checking follow nested logic for +2, +4, and so on for nested conditionals and so on? I imagine this is a little tricky.

`cmake-format` will nest scope "blocks" at increments of `tab_size`, so I think the answer to your question is "yes". However, as mentioned above, there isn't a separate "whitespace checking" in `cmake-format`. The `--check` option just runs the format process but instead of writing out the result, it compares the result to the input content. If they are not identical, then it exits with nonzero status.

**Comment by cheshirekow** [comment]
Enforcing spaces per tab is kind of tough. The default configuration of `cmake-format`, for example, will align wrapped content to the column of the opening parenthesis the enclosing statement. This is often not on a tab-stop and so the number of spaces will no be a multiple of `tab_size`. In fact, determining the correct indentation for the context is exactly the job of `cmake-format`. 

One that that *is* possible is a relaxed check that only enforces "spaces-per-tab" at block scope, and up to the column of the enclosing statement at statement scope. In other words ignore the number of spaces for any wrapping within a statement. I'll have a look at implementing that.
