### ISSUE TITLE
"--separate-fn-name-with-space" does not work properly

### ISSUE THREAD

**Issue by tawmoto** [cheshirekow/cmake_format#212]
Hi,

I run this command
```
cmake-format --line-width=120 --separate-ctrl-name-with-space=true --separate-fn-name-with-space=false --tab-size=4 <file> -i
```

And I see that it adds a space between function name and the parantheses, which seems wrong, I just want space between control flow names.

![image](https://user-images.githubusercontent.com/35702340/86534776-de05d800-bee3-11ea-909d-d57e62b94a5f.png)

Am I doing something wrong?
Thanks

**Comment by cheshirekow** [comment]
Sounds like you are looking for https://cmake-format.readthedocs.io/en/latest/configopts.html#separate-ctrl-name-with-space

**Comment by tawmoto** [comment]
> Sounds like you are looking for https://cmake-format.readthedocs.io/en/latest/configopts.html#separate-ctrl-name-with-space

I set this option as `true`. Shouldn't this apply for flow-control stuff like `if/else`?
Sorry, the documentation is great but sometimes they lack examples and is not clear exactly what an option does.

**Comment by cheshirekow** [comment]
test.cmake:
```
if(FOO AND BAR)
  dothing()
endif()
```

`cmake-format --separate-ctrl-name-with-space=true /tmp/test.cmake`:
```
if (FOO AND BAR)
  dothing()
endif ()
```

`cmake-format --separate-ctrl-name-with-space=false /tmp/test.cmake`
```
if(FOO AND BAR)
  dothing()
endif()
```

> sometimes they lack examples and is not clear exactly what an option does.

Yeah, I would like to add examples as I think they would help illustrate the usage for these but I haven't had the time.

**Comment by cheshirekow** [comment]
Does this example illustrate what you're looking for? Any further questions?

**Comment by tawmoto** [comment]
Hi @cheshirekow , thanks for for the moment we will postpone cmake-format integration in our company project, we still have to analyze some corner cases. I hope I will get back to it soon.
