### ISSUE TITLE
VSCode extension: CMakeLists.txt are not formated

### ISSUE THREAD

**Issue by blackliner** [cheshirekow/cmake_format#228]
With the VSCode extension, only *.cmake files are considered CMake files. But the majority of files are usually CMakeLists.txt

Is there a way to configure the extension to look for CMakeLists.txt files in addition?

**Comment by hofbi** [comment]
Can approve this behaviour. This was introduced with the latest release. Using 0.6.11 is a possible workaround.

Further with the latest release the `cmake-format` binary seems to be missing. I get 

```
whereis cmake-format
cmake-format:
```

With 0.6.11 a binary is there.

**Comment by cheshirekow** [comment]
> Is there a way to configure the extension to look for CMakeLists.txt files in addition?

Add the following to your `settings.json`:

```
{
  "files.associations": {
    "CMakeLists.txt": "cmake",
}}```

**Comment by cheshirekow** [comment]
@hofbi 
> This was introduced with the latest release.

There have been no changes in file associations with the latest release. 

> Further with the latest release the cmake-format binary seems to be missing

The vscode extension has never shipped the binary. The binary should be installed through pip.

**Comment by blackliner** [comment]
> > Is there a way to configure the extension to look for CMakeLists.txt files in addition?
> 
> Add the following to your `settings.json`:
> 
> ```
> {
>   "files.associations": {
>     "CMakeLists.txt": "cmake"
>   }
> }
> ```

Do you mean the `.cmake-format` file one gets when `cmake-format --dump-config > .cmake-format` ?

**Comment by hofbi** [comment]
> Add the following to your settings.json

@blackliner He means the VSCode settings.json

But manually adding this seems to me just like a workarround. Actually one would expect that CMakeLists.txt are by default recognized to be formatted. VSCode itself does this association, right? For instance on my machine I have full CMake support on these files without the file association. However, the format is not happening and I am pretty sure this already worked

**Comment by blackliner** [comment]
I had to uninstall the extension, because both this and C/C++ extension from Microsoft try to format.
