### ISSUE TITLE
Offline install broken because top-level setup.py does not pass arguments

### ISSUE THREAD

**Issue by BaconPancakes** [cheshirekow/cmake_format#250]
Just passing by with a minor issue that should be a quick fix.

I'm work with airgapped systems or systems where pip is blocked by proxy. I can bypass pip by running `setup.py` directly from the package via `python3 setup.py install --user`.

I noticed for this package, the top-level setup.py just invokes `cmakelang/pypi/setup.py`. This breaks the expected behavior of `setup.py` because arguments aren't passed to the actual `setup.py`. The workaround is just to invoke the real `setup.py` directly via `python3 cmakelang/pypi/setup.py install --user`.

Probably it'd be better to use one of the pythonic patterns to invoke a module while passing arguments, or something, but I'm not confident enough to propose an implementation.

**Comment by cheshirekow** [comment]
> I noticed for this package, the top-level setup.py just invokes cmakelang/pypi/setup.py.

This is not correct. The top-level setup.py is a symlink to cmakelang/pypi/setup.py. Are you perhaps running on a system which doesn't properly support symlinks? Like a very old git on windows perhaps?

**Comment by BaconPancakes** [comment]
Ah you're right. I see it clearly in the github as a symbolic link. My Windows settings probably messed with the symlink upon unzip/clone but when I clone it directly in Linux it's a symlink as expected. 

All is well, then.
