### ISSUE TITLE
How to disable formating on comments

### ISSUE THREAD

**Issue by ye-luo** [cheshirekow/cmake_format#251]
Failed to find an option or a workaround.
It will help adopt cmake-format on existing project a lot easier.

**Comment by cheshirekow** [comment]
I think you're looking for `enable_markup`: https://cmake-format.readthedocs.io/en/latest/configopts.html#enable-markup

**Comment by ye-luo** [comment]
Exactly. `--enable-markup FALSE`. Thank you!
