### ISSUE TITLE
`pip install cmakelang` does not install `pyyaml`

### ISSUE THREAD

**Issue by Ipiano** [cheshirekow/cmake_format#266]
I would expect that `pyyaml` would be a requirement of the `cmakelang` package such that I can just run `pip install cmakelang` and immediately start using `cmake-format` with yaml files specifying the configuration.

At the very least, please add to the README file an indicator of which specific version of `pyyaml` must be installed to use this.

**Comment by Ipiano** [comment]
I missed that; sorry! Thank you for pointing me to it

**Comment by nmontmarquette** [comment]
+1 on that issue.
Still, installing it myself doesn't seem to fix the issue of using a .yaml-based config :-/
$ cmake-format --version
0.6.13
