### ISSUE TITLE
Parsing fails in multiline command with (escaped) quotes

### ISSUE THREAD

**Issue by renemilk** [cheshirekow/cmake_format#28]
I'm _really_ looking forward to integrating your project with our workflow. I've been looking for something clang-format-for-cmake-like for years.

Using cmake_format from pypi on python 3.5 in a virtualenv, I've run into a speedbump processing [this file](https://github.com/dune-community/dune-xt-common/blob/82f10882bd95ff25869bece7caac4e2cebcec909/cmake/modules/DuneXTInstallPythonPackage.cmake#L157): 
```
Error while processing OTHERPATH/dune-xt-common/cmake/modules/DuneXTInstallPythonPackage.cmake
While processing OTHERPATH/dune-xt-common/cmake/modules/DuneXTInstallPythonPackage.cmake
Traceback (most recent call last):
  File "SOMEPATH/python-env/bin/cmake-format", line 11, in <module>
    sys.exit(main())
  File "SOMEPATH/python-env/lib/python3.5/site-packages/cmake_format/__main__.py", line 279, in main
    process_file(cfg, infile, outfile)
  File "SOMEPATH/python-env/lib/python3.5/site-packages/cmake_format/__main__.py", line 41, in process_file
    tok_seqs = parser.digest_tokens(tokens)
  File "SOMEPATH/python-env/lib/python3.5/site-packages/cmake_format/parser.py", line 148, in digest_tokens
    tokens[0].line, tokens[0].col))
AssertionError: Unexpected token of type UNQUOTED_LITERAL at 160:38
```
I'm only using defaults for config options atm.

[Installed packages](https://github.com/cheshirekow/cmake_format/files/1815173/pip.freeze.txt)

**Comment by cheshirekow** [comment]
ah, that's a bummer. I bet it's a failure to parse the escaped quotes. Thanks for submitting the example file that will make it much easier to create a test and validate a solution. I'll hopefully be able to address this soon.

**Comment by cheshirekow** [comment]
Ok, the lexing rule for escaped quotes is definitely not working. I think I've got something that works. If you want something quick and don't mind patching the source you can try this:
```
diff --git a/cmake_format/lexer.py b/cmake_format/lexer.py
index 4bb2385..270246c 100644
--- a/cmake_format/lexer.py
+++ b/cmake_format/lexer.py
@@ -68,10 +68,10 @@ def tokenize(contents):
   # behavior of the lexer
   scanner = re.Scanner([
       # double quoted string
-      (r'(?<![^\s\(])"([^\"]|\\[\"])*[^\\]?"(?![^\s\)])',
+      (r'(?<![^\s\(])"[^"\\]*(?:\\.[^"\\]*)*"(?![^\s\)])',
        lambda s, t: (QUOTED_LITERAL, t)),
       # single quoted string
-      (r"(?<![^\s\(])'([^\']|\\[\'])*[^\\]?'(?![^\s\)])",
+      (r"(?<![^\s\(])'[^'\\]*(?:\\.[^'\\]*)*'(?![^\s\)])",
        lambda s, t: (QUOTED_LITERAL, t)),
       # bracket argument
       (r"(?<![^\s\(])\[(=*)\[.*\]\1\](?![^\s\)])",
```
Otherwise, I'll hopefully push an update soon.

**Comment by renemilk** [comment]
I am very happy to report that with this patch all my (valid) cmake files are covered. I'm looking forward for you update so I can use this in production.
Thanks!

**Comment by cheshirekow** [comment]
Fixed in https://github.com/cheshirekow/cmake_format/commit/3c5ab66de8b0f70350d241f14a1127b508a0f76a
