### ISSUE TITLE
Feature idea: Harmonizing of command casing

### ISSUE THREAD

**Issue by renemilk** [cheshirekow/cmake_format#29]
Currently our codebase is almost random in using upper or lower case for commands. It would be really nice if cmake_format had an option to harmonize this as well.

**Comment by cheshirekow** [comment]
Yeah, I like that. Probably similar to line-endings I can imagine some users may want "force upper", "force lower" or "leave unchanged".

**Comment by cheshirekow** [comment]
As of `v0.3.6` there is now a `--command-case` command line option, or `command_case = ` config file option. The allowed values are `lower` (default), `upper`, or `unchanged`.
