### ISSUE TITLE
support stdin as input file

### ISSUE THREAD

**Issue by sum01** [cheshirekow/cmake_format#30]
I'm trying to use the formatter with [vim-autoformat](https://github.com/Chiel92/vim-autoformat) and I'm not seeing what I'm doing wrong.

Error
```
Formatter cmake_format has errors: b'Traceback (most recent call last):\n  File "/usr/bin/cmake-format", line 11, in <module>\n    load_entry_point(\'cmake-format==0.3.5\', \'console_scripts\', \'cmake-format\')()\n  File "/usr/li
b/python3.6/site-packages/cmake_format/__main__.py", line 243, in main\n    ("if more than one input file is specified, then formatting must be done"\nAssertionError: if more than one input file is specified, then formatting must
be done in-place or written to stdout\n'
```

The lines in `init.vim`
```vim
let g:formatdef_cmake_format = '"cmake-format --dangle-parens true --line-ending unix --tab-size 0"'
let g:formatters_cmake = ['cmake_format']
```

I've tried manually running it from the terminal with the same command and on the same file, and it writes to stdout as expected.

---

Side-note, is `--tab-size 0` correct to use tabs instead of spaces? I didn't see anything mentioning tabs/spaces, only that it controlled the number of spaces used.

**Comment by cheshirekow** [comment]
Hm... yeah stdin isn't a feature. Seems like something I would have added but it doesn't look like I did. I'm going to rename this issue to a feature request!

There is no option that uses tabs instead of spaces. If that's something you'd like to see, please submit another feature request!

**Comment by cheshirekow** [comment]
As of `v0.3.6`  use `-` as the input filename and `cmake-format` will read from stdin.
