### ISSUE TITLE
Allow use of tabs instead of spaces

### ISSUE THREAD

**Issue by sum01** [cheshirekow/cmake_format#31]
Some ways I've seen it done is..
1. A `--use-tabs` option that doesn't take input
2. A `--use-tabs` option that takes a `true` or `false`
3. Using tabs when a setting like `--tab-size` is set to `0`

I'd say either 1 or 2 are good choices, because then `--tab-size` can still be used for indent level, just with tabs instead of spaces.

Ref https://github.com/cheshirekow/cmake_format/issues/30#issuecomment-379111042

**Comment by cheshirekow** [comment]
Hm... thinking about this further, I'm not sure what the right way to deal with this would be. For instance the following formatted output is impossible using tabs:

```
command_name(argument_one
              argument_two
              argument_three)
```

because "command_name(" is 13 chars wide. 

Possibly the formatter could push columnized arguments to the next tab stop, but that's going to be more significant of a refactor...

**Comment by sum01** [comment]
Some formatters allow for mixed (spaces & tabs) to be used in situations like that. Of course having a flag to not used mixed (in that situation) would be good if you implement it like that.

If tabs & non-mixed were used, it could indent once past the level of `command_name` with no regard to "perfect" alignment, as you mentioned.

**Comment by AntoinePrv** [comment]
Hello,

I would also be interested to see this feature.
When using tabs, I avoid _"line continuation"_, rather all arguments have their own line.
The example would become
```
command_name(
    argument_one
    argument_two
    argument_three
)
```
This is similar to what [Black](https://black.readthedocs.io/en/stable/), a Python code formatter, does (even if Python is space indented).

**Comment by cheshirekow** [comment]
@antoineprv you may want to have a look at the [`unexpand` program][1].

[1]: http://man7.org/linux/man-pages/man1/unexpand.1.html
