### ISSUE TITLE
Option to always wrap arguments vertically

### ISSUE THREAD

**Issue by oysstu** [cheshirekow/cmake_format#330]
I've been looking at previous issues and trying various combinations of options, but have been unable to format lists of files as one argument on each line. I'd like this for e.g. "include_directories", "add_library", "target_link_libraries" etc regardless of how many arguments there are or how wide the line is.

This might be possible already, any hints?

Essentially, I'd like the following output
```cmake
include_directories(
  "include" 
  ${avformat_INCLUDE_DIRS} 
  ${avcodec_INCLUDE_DIRS} 
  ${avfilter_INCLUDE_DIRS} 
  ${swscale_INCLUDE_DIRS})
```

But I'm getting this, with always-wrap enabled for include_directories
```cmake
include_directories(
  "include" ${avformat_INCLUDE_DIRS} ${avcodec_INCLUDE_DIRS} ${avfilter_INCLUDE_DIRS} ${swscale_INCLUDE_DIRS})
```

**Comment by louwers** [comment]
It is bugged https://github.com/cheshirekow/cmake_format/issues/180

**Comment by oysstu** [comment]
Aha, that explains it. I will close this issue, hopefully the linked issue can be reopened
