### ISSUE TITLE
allow indent earlier

### ISSUE THREAD

**Issue by ingwinlu** [cheshirekow/cmake_format#41]
Currently cmake_format reports it as an error if you indent a line earlier than when it is needed.

For me personally I like to 'overintend' especially with functions and the like that get messy to read otherwise.

It would be great to add an option that would allow this kind of behaviour.

**Comment by cheshirekow** [comment]
Can you provide an example of what you mean? I can't quite picture what you mean by indenting earlier than needed.

**Comment by cheshirekow** [comment]
I'm closing this as I don't have enough information to act upon it. Feel free to reopen if you have time to add more info.
