### ISSUE TITLE
Allow custom string (or list of strings) for rulers

### ISSUE THREAD

**Issue by bergercookie** [cheshirekow/cmake_format#43]
Description is pretty much the same as in https://github.com/cheshirekow/cmake_format/issues/42

Let the user specify the ruler pattern. Perhaps even use a regular expression here:

`let ruler_string_specifiers = ["### .* ###"]`

**Comment by cheshirekow** [comment]
A reasonable request.

FYI: the current ruler regex is:
```
# Matches comment lines that are clearly meant to separate sections or
# headers. The meaning of this regex is "a line consisting of three or more
# non-word characters ending with three or more non-word characters"
RULER_REGEX = re.compile(r'^\s*[^\w\s]{3}.*[^\w\s]{3}$')
```
