### ISSUE TITLE
Leading comments inside function bodies cause errors

### ISSUE THREAD

**Issue by alastair-harrison** [cheshirekow/cmake_format#46]
```bash
$ clang-format --version
0.3.6
```

When I run `cmake-format` on a code block like this:
```cmake
my_function(
  # This comment causes a parse error
  stuff
)
```
`cmake-format` gives me the following error:
```bash
$ cmake-format test.cmake
Error while processing test.cmake
While processing test.cmake
Traceback (most recent call last):
  File "/usr/local/bin/cmake-format", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cmake_format/__main__.py", line 312, in main
    process_file(cfg, infile, outfile)
  File "/usr/local/lib/python3.6/site-packages/cmake_format/__main__.py", line 54, in process_file
    fst = parser.construct_fst(tok_seqs)
  File "/usr/local/lib/python3.6/site-packages/cmake_format/parser.py", line 426, in construct_fst
    block_stack[-1].children.append(Statement(tok_seq))
  File "/usr/local/lib/python3.6/site-packages/cmake_format/parser.py", line 315, in __init__
    assert self.body
AssertionError
```

**Comment by cheshirekow** [comment]
Fixed I believe in the next release. If you're able please try https://github.com/cheshirekow/cmake_format/releases/tag/v0.4.0rc1 and let me know how it goes

**Comment by alastair-harrison** [comment]
Yes, it now formats the file without crashing. The result still looks a bit funny:
```cmake
my_function(# This comment causes a parse error
            stuff)
```
Would probably have expected the comment to stay on its own line, because it refers to `stuff`, rather than `my_function`.

**Comment by cheshirekow** [comment]
The comment is given it's own line (however that line is the first in the column, packed on the same line as the function). If it refers to `stuff` you may prefer the formatting if you put the comment on the same line as stuff, immediately following it, i.e. `stuff # This comment...`. 

The original formatting of:
```
my_function(
  # this comment...
  stuff
)
```
would be what `cmake-format` would select if the first try didn't fit. In the future, the order of precedence will be configurable.
