### ISSUE TITLE
cmake-format removes entire while()... endwhile() sections

### ISSUE THREAD

**Issue by bergercookie** [cheshirekow/cmake_format#49]
There seems to be a scary bug when running cmake-format in scripts that use `while(...)` loops! cmake-format just removes them!

Sample file:

```cmake

set(A "a")


while(condition)
    fun1()
    fun2()
endwhile()

set(B "b")

```

If you run cmake-format on the latter we end up with this:

```cmake

set(A "a")



set(B "b")


```

Any pointers?

**Comment by cheshirekow** [comment]
Fixed I believe in the upcoming release. If you're able, please try https://github.com/cheshirekow/cmake_format/releases/tag/v0.4.0rc1 and lte me know how it goes

**Comment by bergercookie** [comment]
looks fine.
Thanks.
