### ISSUE TITLE
Allow configurable preference for layout priority. 

### ISSUE THREAD

**Issue by mathstuf** [cheshirekow/cmake_format#5]
It seems that the prevailing style here is:

```cmake
some_long_command_name(arg arg arg
                       arg)
```

It'd be nice to have an option for this instead:

```cmake
some_long_command_name(arg arg arg
  arg)
```

**Comment by cheshirekow** [comment]
This is already supported actually! Well sort of. It's just not very tuneable yet. Currently the indentation you're describing is the final fallback if none of the other strategies fit in the desired column width, or if it uses way fewer lines. It would be nice to make this more tunable/selectable as a preference.

**Comment by jslee02** [comment]
It would be also good to have this style:
```cmake
some_long_command_name(arg arg arg
  arg
)
```

**Comment by cheshirekow** [comment]
I'm open to the dangling parenthesis as an option. @jslee02 please open a new issue.

**Comment by jslee02** [comment]
Created #13.

**Comment by cheshirekow** [comment]
You can do this now with the `algorithm_order` option. Try `algorithm_order=[0, 2, 3]` and see if that provides what you want.
