### ISSUE TITLE
Indented comments incorrectly appended to preceding line

### ISSUE THREAD

**Issue by mikew-lunarg** [cheshirekow/cmake_format#50]
This may be a different aspect of issues #46 and #47

If a comment is already indented, cmake-format seems to consider it as an end-of-line comment for the previous line and appends it to that previous line.

Given this original input file f0.txt, where the `if(A)` block is unformatted, and the `if(E)` block is already correctly formatted:
```
$ cmake-format --version
0.3.6

$ cat f0.txt 
if(A)
# comment about B
baz(B)
# comment about C
baz(C)
endif()

if(E)
  # comment about F
  baz(F)
  # comment about G
  baz(G)
endif()
```
Running cmake-format on f0.txt to generate f1.txt, where the `if(A)` block is correctly formatted, but the `if(E)` block now has comments incorrectly appended to the previous lines:
```
$ cmake-format f0.txt | tee f1.txt
if(A)
  # comment about B
  baz(B)
  # comment about C
  baz(C)
endif()

if(E) # comment about F
  baz(F) # comment about G
  baz(G)
endif()
```
Running cmake-format again with the previous output f1.txt to generate f2.txt, where both `if(A)` and `if(E)` blocks have comments incorrectly appended to the previous lines:
```
$ cmake-format f1.txt | tee f2.txt
if(A) # comment about B
  baz(B) # comment about C
  baz(C)
endif()

if(E) # comment about F
  baz(F) # comment about G
  baz(G)
endif()

$ diff -q f1.txt  f2.txt 
Files f1.txt and f2.txt differ
```

**Comment by mikew-lunarg** [comment]
My repro files
[cmake-format_issue50.zip](https://github.com/cheshirekow/cmake_format/files/2146843/cmake-format_issue50.zip)

**Comment by cheshirekow** [comment]
Fixed I believe in the upcoming release. If you're able, please try https://github.com/cheshirekow/cmake_format/releases/tag/v0.4.0rc1 and lte me know how it goes

**Comment by mikew-lunarg** [comment]
How does one build/run from tarball?  I installed v0.3.6 from pip.

**Comment by cheshirekow** [comment]
It's pure python so there's no build, and there's a number of ways mostly depending on your preference. My suggestion would be to extract the tarball somewhere temporary and then use the `PYTHONPATH` environment variable to point to that location. If you're on a linux/mac here's what I would do:

```
$ cd /tmp/
$ wget https://github.com/cheshirekow/cmake_format/archive/v0.4.0rc1.tar.gz
$ tar xf v0.4.0rc1.tar.gz
$ cd ~/path/to/your/project
$ PYTHONPATH=/tmp/v0.4.0rc1 python -Bm cmake_format ./path/to/CMakeLists.txt
```

**Comment by mikew-lunarg** [comment]
Thanks, those run instructions were very helpful.  Perhaps insert in the docs somewhere ;-)

I believe rc1 addresses the original topic of this issue.
I like your refinements to the formatting layout.

I've discovered a couple other things in rc1, which I'll mention here.  (Let me know if you'd prefer I close this and start another issue)

1. [# cmake-format: off](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Loader/loader/CMakeLists.txt#L285) gets indented, the matching [# cmake-format: on](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Loader/loader/CMakeLists.txt#L299) remains unindented.  Personally I prefer them both unindented as before.
1. This [set()](https://github.com/mikew-lunarg/cmake_stuff/blob/v040rc1/KhronosGroup/Vulkan-Tools/cube/macOS/cubepp/cubepp.cmake#L25) command is formatted very differently than other set() commands before and after.  Not clear why.

Thanks very much!

**Comment by cheshirekow** [comment]
Ok great, thanks for testing that out. I think it's fine for us to discuss those new issues here. I have an idea of why (1.) is doing what it's doing. I'll add a test for that and should be able to fix it quickly. I'm not sure about that `set()` though... 

Thanks for the linking the file. I'll give it a try myself and dig into what's going on with that one.

**Comment by mikew-lunarg** [comment]
starting new issue for 0.4.0rc1

**Comment by mikew-lunarg** [comment]
(sorry, we crossed in flight, see #51)

**Comment by cheshirekow** [comment]
No worries, sounds good.
