### ISSUE TITLE
override config file option not up to date in readme

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#52]
There are some new configs to set in the Configuration section, 

dangle_parens = False
bullet_char = u'*'
enum_char = u'.'
line_ending = u'unix'
command_case = u'lower'

but they are not mentioned in the Usage -->  Override configfile options section. It should be updated as well. I guess some of them myself like `cmake-format --command-case upper CMakeLists.txt` and it actually works.

Normally I will do a PR for this but I know PR is generally not accepted in this repo.

**Comment by cheshirekow** [comment]
This is fixed in `0.4.0`.
