### ISSUE TITLE
Incorrect Formatting of Function Call With Interspersed Comments

### ISSUE THREAD

**Issue by sanssecours** [cheshirekow/cmake_format#55]
# Steps to Reproduce

1. Create a file `test.cmake` with the following content

   ```cmake
   cmake_parse_arguments(ARG
                         "SILENT" # optional keywords
                         "" # one value keywords
                         "" # multi value keywords
                         ${ARGN})
   ```

2. Create a configuration file `.cmake-format.yaml` with the following content

   ```yaml
   line_width: 140
   ```

3. Run `cmake-format`

   ```sh
   cmake-format test.cmake
   ```

# Expected Result

The command `cmake-format` prints a nicely formatted version of the given CMake code.

# Actual Result

The command produces the following syntactically incorrect code:

```cmake
cmake_parse_arguments(ARG "SILENT" # optional keywords "" # one value keywords "" # multi value keywords ${ARGN})
```

.

**Comment by cheshirekow** [comment]
Hm.. I thought this was covered in unit testing but I guess not. Thanks for the report. Should be easy to fix.
