### ISSUE TITLE
Support keyword/value alignment

### ISSUE THREAD

**Issue by mathstuf** [cheshirekow/cmake_format#6]
For commands with many keyword arguments, it can be nice to align the values to the keywords like this:

```cmake
some_command(
  KEYWORD       arg
  MULTI_KEYWORD arg
                arg)
```

Where values are aligned to indentation levels. Combined with #5, it could look like this:

```cmake
some_command(
  KEYWORD
    arg
  MULTI_KEYWORD
    arg
    arg)
```

The `MULTI_KEYWORD` arguments could also be collapsed to a single line following line length limits.

**Comment by jasjuang** [comment]
It will be great to have this functionality!

**Comment by cheshirekow** [comment]
Already implemented! (unless I'm missing what you mean). You need to specify what are the keywords though. You specify them through the configuration file. See [cmake_format/test/cmake-format.yaml](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/test/cmake-format.yaml) for example. In this case the custom command is like `foo(arg BAR arg arg BAZ arg arg)`. 

I originally made it so that unconfigured commands would assume all-caps as keyword arguments. I wouldn't be opposed to making that the default. I wouldn't be opposed to making that an option again. Please open a new issue if that is something you'd like to see. 

Most of the cmake built-ins are already configured. See `commands.py` if you'd like to contribute new built-ins.

**Comment by mathstuf** [comment]
Ah, I see now. However, that test has all the keywords of the same length and inter-arg alignment isn't displayed.

Also, in that test, the output shows this:

```cmake
set_target_properties(foo bar baz
                      PROPERTIES COMPILE_FLAGS "-std=c++11 -Wall -Wextra")
```

however, with multiple properties this gets unwieldy (depending on the pattern this follows):

```cmake
set_target_properties(foo bar baz
                      PROPERTIES COMPILE_FLAGS "-std=c++11 -Wall -Wextra" COMPILE_DEFINITIONS FOO)
```

There may need to be a special way to indicate that `PROPERTIES` takes a series of pairs of arguments (maybe `*2` as the specifier?). Other oddballs include the `ARCHIVE`, `LIBRARY`, etc. group-y arguments in the `install` command.

**Comment by jasjuang** [comment]
@cheshirekow @mathstuf I still don't fully understand how the additional commands work. Using the example `foo(arg BAR arg arg BAZ arg arg)`, if I want it to look like 

```
foo(     arg
  BAR  arg
           arg
  BAZ  arg
           arg)
```

What should my additional commands be?

```
"additional_commands":
    {
        "foo":
        {
            "flags": ["BAR", "BAZ"],
            "kwargs":
            {
                "HEADERS": "*", ---> How are these three headers, sources, depends related to the argument? Should I put a string or a digit here? What does the string or digit represents?
                "SOURCES": "*",
                "DEPENDS": "*"
            }
        }
    }
```

**Comment by cheshirekow** [comment]
@jasjuang I apologize, I gave a poor example. The example should be more like

`foo( HEADERS arg1 arg2 arg3 BAR BAZ SOURCES arg1 arg2 arg3)`

The specification for a custom command takes three parts:

* `pargs`: number of expected positional arguments
* `kwargs`: keywords that are expected to be followed by some number of arguments. In the map, you put the number of arguments expect. `+` means one or more, `*` means zero or more. 
* `flags`: a list of tokens which are sentinel only, they only have meaning in the fact that they exist or not. These could also be specified in `kwargs` with a value of `1`.

Note that the intention of the command specification is not fully realized. The idea is that cmake-format can be smart about how to format a command if it knows about the argument specification of that command. However I haven't really implemented much of that smart-ness yet. 

@mathstuff yeah I haven't figured out a good solution yet for argument "nesting" (kwargs that take kwargs). What I have currently implemented is that if the parser encounteres a new kwarg token it completely drops out of the current kwarg that it is collecting tokens for. This means that `cmake-format` just treaks `COMPILE_COMMANDS` as an argument to `PROPERTIES` in your example. 

One thing that I've been considering is to allow arbitrary nesting of kwargs. In that case the parser has a stack context where each time a kwarg is encountered it pushes a new specification on the stack for kwargs to look for. I'm hoping to experiment with that idea soon.

**Comment by mathstuf** [comment]
[This issue](https://gitlab.kitware.com/cmake/cmake/merge_requests/1746) may be of interest then :) .

**Comment by jasjuang** [comment]
@cheshirekow Thanks for the explanation. I will wait till the command specification is fully realized then I will give it a test and see if it's working as I imagined.
