### ISSUE TITLE
Consider option to not reflow initial comment block

### ISSUE THREAD

**Issue by coryan** [cheshirekow/cmake_format#60]
Our CMake list files start with a copyright block. It would be desirable to have an option that prevents reflow of the first comment block on a file.  I can use fences (`# ~~~`) to work around this, but that seems unnecessarily ugly, maybe?

Thanks for the great tool btw.

**Comment by coryan** [comment]
> enforce/ensure that the first comment is literally exactly as the project requires? For instance maybe a config option like `copyright_text="""..."""` and then cmake-format ensures that the first comment is literally that same text?

The standard in our project is to put a copyright block based on the year when the file was *created*. As they are not all identical. For extra fun, sometimes the legal entity changes, and in our case we have been asked to keep the old legal entity in old files, and use the new one in newer files.

So it would need to be something like `copyright_line_regexp=...` and `copyright_text=...` I would think.

> Incidentally, do you mind pasting or sending me the content of your copyright block?
Here is one of our copyright messages:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/64a8899a3b67893fc5fd5da97b3a83258d12891c/CMakeLists.txt#L2

**Comment by mikew-lunarg** [comment]
>
> Ok yeah, copyright blocks are important. I'm wondering which would be
> better, an option to ignore the first comment, as you requested, or would
> it be better to enforce/ensure that the first comment is literally exactly
> as the project requires? For instance maybe a config option like
> copyright_text="""...""" and then cmake-format ensures that the first
> comment is literally that same text? It might be hard to ensure that we
> detect "old" instances of the copyright comment and remove them in order to
> replace the.
>
This issue is a cool suggestion, and could help enforce the style that the
first thing in EVERY source file should be a comment :-)

I'd agree w @coryan that matching exact copyright strings would be
non-optimal.  There may start as standard boilerplate, but individual
blocks will change due to updated dates and contributors.

Another sample for your reference:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/CMakeLists.txt
but I'd caution against trying to regexp.

cheers
-- mew

**Comment by cheshirekow** [comment]
> The standard in our project is to put a copyright block based on the year when the file was created. As they are not all identical. For extra fun, sometimes the legal entity changes, and in our case we have been asked to keep the old legal entity in old files, and use the new one in newer files.

Ok these are very good points. It's probably best just to keep the first comment literally as you originally requested. 

Looking at your listfile and at @mikew-lunarg's it looks like there are two things undesirable about the current behavior:

1. your copyright block wraps to a different columnwidth than the rest of the document
2. the license url is indented... block-quote style

So one question: is `1.` really desirable? I'm inclined to think that the copyright text should wrap to the same column as the rest of the document... unless there's some reason that the exact line break locations are important to maintain. 

And for `2.`, this sounds like a good thing to enable support for in the comment markup parsing/formatting in general. 

That said, I'm still on board with a `first_comment_is_literal` or `rights_comment_is_literal` option. Maybe a comment is a rights comment if it is the first comment in a file and it contains the words `Copyright` or `License`. But maybe that's over-complicating things and `first_comment_is_literal` is simpler and therefore better.

**Comment by mikew-lunarg** [comment]
A glib answer to (1) is "lawyers".  I prefer to leave that block completely alone, as I enforce with the `# ~~~` fences.   At the start of a year, while folks are updating the dates, I think it would be preferable for all our source files (not just CMake) to have similar formatting, to be at least approximately diffable.  FWIW I believe I lifted that copyright from a .cpp file.  We definitely wouldn't want reflowing of e.g. the named copyright holders and the date.

Personally, I'm fine w the `# ~~~` fences as is.

**Comment by coryan** [comment]
> So one question: is `1.` really desirable? I'm inclined to think that the copyright text should wrap to the same column as the rest of the document... unless there's some reason that the exact line break locations are important to maintain.

"Desirable"? No. "Necessary"? Maybe.

I am not sure how strict the folks that enforce our policies w.r.t. licensing and copyright are about the formatting of these.  There must be some leeway, because each language uses different comment characters for example. But without a lot of research the ~safest/easiest~ laziest thing for me to do is keep the formatting exactly as-is.

> But maybe that's over-complicating things and `first_comment_is_literal` is simpler and therefore better.

I think that would meet most folks needs, at least it would work for me.

Thanks so much for putting this tool together btw.

**Comment by cheshirekow** [comment]
@coryan @mikew-lunarg I'm currently debating between:

1. the first comment of every listfile
2. any comment that starts with a user specified regex (i.e. `Copyright.*`)
3. first comment of every listfile that matches a user specified regex

`2` seems like the most general, and would allow the comment to come after some other thing. Also would be easiest to implement with the current system. `1` seems to most directly address your guys
use cases. `3` would probably limit some false positive cases but probably shouldn't be necessary right?

Hm... thinking about it more... Maybe I'll just do both `1.` and `2.`...
