### ISSUE TITLE
format elseif like if

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#63]
Currently in my CMakeLists.txt there is something like

```
if((CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
   OR CMAKE_COMPILER_IS_GNUCC
   OR CMAKE_COMPILER_IS_GNUCXX)

endif()
```

After reformatting by cmake-format it keeps it the same, which is great. But for the below

```
if(MSVC)

elseif((CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
       OR CMAKE_COMPILER_IS_GNUCC
       OR CMAKE_COMPILER_IS_GNUCXX)

endif()
```
it got reformats to 

```
if(MSVC)

elseif((CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
       OR
       CMAKE_COMPILER_IS_GNUCC
       OR
       CMAKE_COMPILER_IS_GNUCXX)

endif()
```

which imo is less readable. Is it possible to change it so elseif gets treated similarly like if?

**Comment by cheshirekow** [comment]
Yeah, "elsif" is missing from [here](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/commands.py#L552). I'll add in the next release. If you need a quick fix try this in your configuration file (python format):

```
from cmake_format import commands

additional_commands = {
  "elseif" : {
    "flags" : list(commands.CONDITIONAL_FLAGS),
    "kwargs" : {
      "AND" : "+",
      "OR" : "+"
    }
  }
}
```
