### ISSUE TITLE
Possible improvement on formatting "string"

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#64]
Currently in my CMakeLists.txt there is something like

```
string(REPLACE "/w44668" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
```

After reformatting by cmake-format it becomes

```
  string(REPLACE "/w44668"
                 ""
                 CMAKE_CXX_FLAGS
                 "${CMAKE_CXX_FLAGS}")
```

which imo is less readable. Is it possible to change it so it doesn't line break if everything can be fitted to one single line?

**Comment by cheshirekow** [comment]
Set [`max_subargs_per_line`](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/doc/README.rst#configuration) in your config file, or [`--max-subargs-per-line`](https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/doc/README.rst#usage) on the command line. The default I believe is 4, which is leading to the vertical formatting. 

Example:
```
echo 'string(REPLACE "/w44668" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")' | cmake-format --max-subargs-per-line=5 -
string(REPLACE "/w44668" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
```

**Comment by jasjuang** [comment]
Thanks, it works
