### ISSUE TITLE
should warn if `cmake-format: off` doesn't have corresponding `on`

### ISSUE THREAD

**Issue by johannkoenig** [cheshirekow/cmake_format#65]
https://aomedia-review.googlesource.com/c/aom/+/65362/1/test/test.cmake

At the end of the file, running cmake-update removed the entire block after
`# cmake-format: off`

**Comment by cheshirekow** [comment]
Yikes, thats not good. Will investigate and report back.

**Comment by cheshirekow** [comment]
You're missing a space in `# cmake-format: on`. That's tricky... `cmake-format` should deal with this a bit better. At least error out indicating that there is an unterminated `# cmake-format: off`.

**Comment by johannkoenig** [comment]
Ah, thanks! Adding a space before 'on' fixed that!
