### ISSUE TITLE
Can you document the guide to setup developing environment for developers

### ISSUE THREAD

**Issue by jimfang** [cheshirekow/cmake_format#69]
I found there is some bundle to setup a developing environment on my machine.
Suggest adding this part to Readme.

If anyone wants to debug or contribute to this project, help them quickly setup the environment

**Comment by sum01** [comment]
Just by looking at the repo, I'd say you want to use Python 3, format the code with Pep8, and make sure it passes Pylint's lints. How you get those things depends on the OS.

**Comment by jimfang** [comment]
Thanks, Cheshirekow.

I have a development environment for other python projects. (window10, vs
code, python 3).

For cmake-format project, I download it to my local pc.
If I want to debug and add some code, not figure out with normal vs code
launch.json.

How do you setup debugging env for the project?  As vs code is very
popular, do u have a try?

**Comment by cheshirekow** [comment]
I've updated the read me with some notes on development. Pasting here for your convenience:

```
Some notes for anyone who wants hack on ``cmake-format``:

1. Please use ``pylint`` to check your code. There is a pylint config file in
   the repo.
2. There is a test suite in ``tests.py``. Run with
   ``python -Bm cmake-format.tests`` (ensure modified code is on the python
   path).
3. There's an ``autopep8`` config file in the repo as well. Feel free to use
   that to format the code. Note that ``autopep8`` and ``pylint`` disagree
   in a few places so using ``autopep8`` may require some manual edits
   afterward.
4. There's a cmake configuration for the project. Since this is a python
   project there isn't much that it really does but it provides targets for
   ``format``, ``lint`` and ``test`` if you'd like to use them.
```

There's really not much more to say. I use vscode for development these days but I mostly use it as an editor and don't take much advantage of it's integrated tools. I don't use launch.json or tasks.json for this project.
