### ISSUE TITLE
Spaces after control flow commands

### ISSUE THREAD

**Issue by mathstuf** [cheshirekow/cmake_format#7]
I like to have spaces between the command and parentheses for control flow commands (`if`, `elseif`, `else`, `endif`, `while`, `endwhile`, `foreach`, `endforeach`, `continue`, `break`, `return`, `function`, `endfunction`, `macro`, `endmacro`). Having a toggle to preserve that would be nice to have.

**Comment by cheshirekow** [comment]
Sounds like a reasonable request.
