### ISSUE TITLE
cmake doc project cannot compile on windows with MS Visual Studio 2017

### ISSUE THREAD

**Issue by jimfang** [cheshirekow/cmake_format#72]
Reproduce steps:
1.  Create build folder in cmake_format (clone from github)
2.  Open cmd windows
3.  In the path of build, type command "cmake .."
4.  Open cheshirekow.sln with MS Visual Studio 2017
5.  Compile "All_BUILD" success.
6.  Compile doc or cmake_format_doc, The same error (Refer to below image) occurred. 

![cmake-doc-not-work](https://user-images.githubusercontent.com/3314298/46182412-0922c700-c30f-11e8-8cfe-4e5256b3adf7.PNG)

**Comment by cheshirekow** [comment]
Try the `cmake_format_doc` target instead.

**Comment by jimfang** [comment]
Thanks. It works by git clone the repository again with enabling symlinks.

![git-clone-symlinks](https://user-images.githubusercontent.com/3314298/46274319-5c5d7980-c59c-11e8-87e6-114d34514c2d.PNG)
