### ISSUE TITLE
shebang in cmake scripts

### ISSUE THREAD

**Issue by Chingyat** [cheshirekow/cmake_format#74]
Hi.

I have a cmake script with a shebang on the first line, like

```cmake
#!/use/bin/cmake -P
```
After running `cmake-format` on this file, it becomes

```
# !/usr/bin/cmake -P
```
Is it possible to preserve the shebang without totally disabling comment formatting?

**Comment by cheshirekow** [comment]
Try `--first-comment-is-literal` or  `--literal-comment-pattern "#!.*"` and see if that helps. Though I think recognizing and preserving shebang is a thing cmake-format should do.

**Comment by Chingyat** [comment]
Thank you.

`--first-comment-is-literal true` works.

`--literal-comment-pattern "#!.*"` results in an error:
```
cmake-format: error: argument --literal-comment-pattern: invalid NoneType value: '#'
```

**Comment by cheshirekow** [comment]
Ok, the error with `--literal-comment-pattern` I think is a mishandling of the argparse setup. You can use the same option from a config file if you want to give it a try. Otherwise it sounds like `--first-comment-is-literal` will work for you for now.

**Comment by cheshirekow** [comment]
Note to self: see argparse bug in comment.

**Comment by cheshirekow** [comment]
`0.4.4` implements the feature to preserve shebang if it's the first line. Also fixes the `--literal-comment-pattern` command line bug.
