### ISSUE TITLE
configurable positionning of flags ?

### ISSUE THREAD

**Issue by djobet** [cheshirekow/cmake_format#75]
For example, the following code
```
add_library(lib STATIC
                   file1.cc
                   file2.cc
                   [big list of files so it's not layed out horizontally])
```
is changed into
```
add_library(lib
                   STATIC
                   file1.cc
                   file2.cc
                   [big list of files so it's not layed out horizontally])
```

I'd rather have STATIC be kept on the 1st line as I think it belongs semantically there.

Is there any way to do this already or does it needs a change of code ?

**Comment by cheshirekow** [comment]
Can you let me know what version you're using, your config file (if any), and the command you ran? On version `0.4.3` I see the following:
```
$ xclip -o -sel clip | cmake-format -
add_library(lib
            STATIC
            file1.cc
            file2.cc
            [big
            list
            of
            files
            so
            it's
            not
            layed
            out
            horizontally])
```

**Comment by djobet** [comment]
Hello,

Thank you for your answer !

I use cmake-format 0.4.3.

Please find the used cmake-format config file below
[cmake-format.txt](https://github.com/cheshirekow/cmake_format/files/2478677/cmake-format.txt)

So, in my precedent attempt, I messed up the layout : I have the same behaviour as you have with everything aligned.

As you have guessed, I just want the lib name to be on the same line as the STATIC|SHARED flags.
Trying with STATIC:"*" gives the following :

    add_library(lib
                       STATIC file1.cc
                                    file2.cc
                                    [big list of files so it's not layed out horizontally])

Trying with "STATIC" : 0 does not change the original layout

PS : my layout is still messed up.
In the preceding example, STATIC is aligned with lib and file2.cc is aligned with file1.cc

**Comment by cheshirekow** [comment]
Yeah, I think this packing style is useful in some other contexts as well. I'll see if I can figure out a good way to add it.

**Comment by cheshirekow** [comment]
FYI I think this will be easier to implement after a refactor of the command specification. I have a plan to change this specification to increase the granularity of positional argument parsing in support of this and of #78. This wont be added in the next release but hopefully the one after.

**Comment by djobet** [comment]
Would be nice thanks !

**Comment by cheshirekow** [comment]
FYI: In the upcoming release the parse for `add_library` has changed such that `<libname> [STATIC|SHARED] [EXCLUDE_FROM_ALL` are grouped together, and source files are grouped separately. This allows wrapping to be applied to each group. 

```
  def test_add_library_with_optionals(self):
    self.do_type_test("""\
      add_library(foo STATIC EXCLUDE_FROM_ALL foo.cc bar.cc)
      """, [
          (NodeType.BODY, [
              (NodeType.WHITESPACE, []),
              (NodeType.STATEMENT, [
                  (NodeType.FUNNAME, []),
                  (NodeType.LPAREN, []),
                  (NodeType.ARGGROUP, [
                      (NodeType.PARGGROUP, [
                          (NodeType.ARGUMENT, []),
                          (NodeType.FLAG, []),
                          (NodeType.FLAG, []),
                      ]),
                      (NodeType.PARGGROUP, [
                          (NodeType.ARGUMENT, []),
                          (NodeType.ARGUMENT, []),
                      ]),
                  ]),
                  (NodeType.RPAREN, []),
              ]),
              (NodeType.WHITESPACE, []),
          ]),
      ])
```

While not exactly implementing the feature requested, it does yield the desired behavior:

```
$ echo "add_library(foo STATIC EXCLUDE_FROM_ALL a.cc b.cc d.cc e.cc f.cc g.cc h.cc i.cc j.cc)" | python -Bm cmake_format -
add_library(foo STATIC EXCLUDE_FROM_ALL
            a.cc
            b.cc
            d.cc
            e.cc
            f.cc
            g.cc
            h.cc
            i.cc
            j.cc)
```
And it will make it easier to achieve further customization of the formatting behavior.

**Comment by djobet** [comment]
Thanks a lot !
