### ISSUE TITLE
There is no selection formatter for 'cmake'-files installed

### ISSUE THREAD

**Issue by jeremyong** [cheshirekow/cmake_format#83]
When attempting to format/indent a line, region, or file, I get the error in the title. I am using VSCode on Linux with the Vim extension and haven't yet tested it on other platforms.

**Comment by jeremyong** [comment]
Also, cmake-format is installed (via pip) and in the path

**Comment by cheshirekow** [comment]
This is not yet supported by the backend. It's close though. Once implemented in the backend `cmake-format` I'll figure out how to plumb it through the vscode extension.

**Comment by cheshirekow** [comment]
> When attempting to format/indent a line, region, or **file**, I get the error

Actually, this is expected for line/region but for a whole file? That should work. You tried with the `Format Document` command?

**Comment by jeremyong** [comment]
I haven't tried the `Format Document` command yet. The error in the original issue pops up because I hit the "=" character religiously editing in vim mode (which indents a line or highlighted region)

**Comment by cheshirekow** [comment]
Oh, so this sounds like a warning message or error that comes from the vim extension and not vscode itself. I'm not familiar with the VIM extension so I guess the first question is: have you configured it an any way to suggest that there *is* a selection formatter for cmake? 

The `cmake-format` vscode extension registers itself as a `DocumentFormattingEditProvider` using the  [Formatting API](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices). it does not advertise itself as a `DocumentRangeFormattingEditProvider` (which is presumably what the VIM extension means when it says "selection formatter"). 

Without any additional insight, my random guess is that the VIM extension is incorrectly assuming that all formatter extensions are both??

**Comment by cheshirekow** [comment]
@jeremyong can you confirm the status of this issue? Is it the case that this warning message is coming from the VIM plugin? And if so, is the vim plugin just saying that your command is bound to nothing?

**Comment by jeremyong** [comment]
It's still an issue without the vim plugin. If you highlight a region and run the command "Format Selection" you should see the error I believe.

**Comment by cheshirekow** [comment]
Oh you're talking about this infobox:

![image](https://user-images.githubusercontent.com/1309820/53605152-6eebd700-3b6b-11e9-9e8e-80414d365361.png)

which is not an error... just a true statement. So I guess you're just requesting to implement region formatting...

And what about `Format Document`? That works right?

**Comment by cheshirekow** [comment]
Closing this issue. If you feel there is more to discuss feel free to comment further.
