### ISSUE TITLE
Take your contact

### ISSUE THREAD

**Issue by MaximFisherman** [cheshirekow/cmake_format#84]
Take me some your contact. I want to ask you some question about your cmake_format.

**Comment by cheshirekow** [comment]
I'm happy to answer any of your questions here on github. Please feel free to ask questions in this thread.

**Comment by MaximRybak** [comment]
Yes, What algorithm you use when you create that cmake formatter ?

**Comment by cheshirekow** [comment]
You can read more about it [in the documentation](https://cmake-format.readthedocs.io/en/latest/format_algorithm.html)

**Comment by MaximRybak** [comment]
Thanks, a lot. What resources you used to make that algorithm. May be you recommended some books or helpful links ? I will be grateful.

**Comment by cheshirekow** [comment]
Hm... that's a bit of a tough question. I guess it's somewhat novel based on experience, but I'm sure I took inspiration from a number of places. 

You may want to read *The TeX Book* by donald knuth. It's about typesetting, not text formatting, which is a much harder problem. Some of the principles I think are familiar and provide some inspiration. *Introduction to Algorithms* by Cormen, Leisersen, Rivest, and Stein (CLRS) is a very good book on algorithms in general. When I took that class in school we covered some "pretty printing" style algorithms so perhaps there is something specific in that book that would be informative. Lastly, I think there's some documentation around on the internet about the algorithm behind `clang-format`. You might investigate that for more reading.
