### ISSUE TITLE
hash-rulers are stripped from comments even if markup processing is disabled

### ISSUE THREAD

**Issue by Flow86** [cheshirekow/cmake_format#87]
Hi,
an option to disable comment reformatting completly would be nice to have

**Comment by cheshirekow** [comment]
There is a [command line flag](https://cmake-format.readthedocs.io/en/latest/#usage) `--enable-markup` and a [config option](https://cmake-format.readthedocs.io/en/latest/#configuration) `enable_markup=`. If either of these is not working for you please let me know.

**Comment by Flow86** [comment]
Hi,
I've already used "--enable-markup=False", but still get some comment changes:

```
################################################################################
# Custom targets
################################################################################
```

will be formatted to

```
#
# Custom targets
#
```

**Comment by cheshirekow** [comment]
Ok, I see. With `--enable-markup=False` this should not be happening. I'll take a look.
