### ISSUE TITLE
bug with reformatting

### ISSUE THREAD

**Issue by Flow86** [cheshirekow/cmake_format#88]
Hi,
i recently tried to reformat a larger CMakeLists.txt (https://github.com/Return-To-The-Roots/s25client/blob/master/CMakeLists.txt) and found a formatting error here:

```
option(RTTR_BUILD_UPDATER "Build auto-updater. Not advised when changing the default paths as the updater is configured specifically for the official builds." ${RTTR_BUILD_UPDATER_DEF})
```

will be formatted to

```
option(RTTR_BUILD_UPDATER "Build auto-updater. Not advised when changing the default paths as the updater is configured specifically for the official builds."
```
which corrupts the cmake file completly

**Comment by cheshirekow** [comment]
Can you share your command line and config options? With version `0.4.4` and default config I get the following:

```
option(
  RTTR_BUILD_UPDATER
  "Build auto-updater. Not advised when changing the default paths as the updater is configured specifically for the official builds."
  ${RTTR_BUILD_UPDATER_DEF})
```

**Comment by Flow86** [comment]
Hi,

Okay, I checked again if I use 0.4.4 too, so thats the case.
The weird thing is, I can't reproduce the problem now anymore.

I reformatted the file a various times with different options (to find the best options) and at the end the mentioned part was missing.

Perhaps it had something to do with different line lengths and the comment directly in the next line after it. The file also had different line endings here and then, perhaps that was another reason for it.

If I find another file with such a problem, I'll tell you.

Keep up the good work!

**Comment by cheshirekow** [comment]
Ok got it. A comment immediately following a statement or argument has been the source of a few issues in the past, so that could certainly have been part of the trigger. I'm glad you are able to move forward, but if you rediscover the config settings that led to the problem please let me know.
