### ISSUE TITLE
Allow individual configurations to be passed from the command line instead of just from a config file

### ISSUE THREAD

**Issue by jasjuang** [cheshirekow/cmake_format#9]
First of all I want to thank you for making this awesome tool. I also made a [sublime plugin]( https://github.com/jasjuang/sublime_cmake_format) based on this which can run `cmake-format` automatically on save and I hope you will also find it useful. 

Would it be possible to allow individual configurations to be passed from the command line instead of just from a config file? Kind of like what clang-format is [doing]( http://clang.llvm.org/docs/ClangFormatStyleOptions.html). The reason why it's good to have this functionality is because it allows me to support custom configuration in my sublime plugin so no `.cmake-format` or `cmake-format.yaml` is needed as long as you are using sublime.

**Comment by cheshirekow** [comment]
I think it can certainly support command line flags for the flaggy configuration options. Probably thing likes custom commands can't be expressed efficiently on the command like though.

**Comment by jasjuang** [comment]
To be honest with you I still don't fully understand how the `additional_commands` works so I would imagine it being a bit hard to pass to the command line. If there is a more detailed explanation or some examples on how `additional_commands` works that will help tremendously.
