### ISSUE TITLE
release newest version to vscode

### ISSUE THREAD

**Issue by gocarlos** [cheshirekow/cmake_format#90]
currently the newest release here is 0.4.4, on [vscode](https://marketplace.visualstudio.com/items?itemName=cheshirekow.cmake-format#overview) we have 0.4.2

**Comment by cheshirekow** [comment]
The vs extension has not changed so there's nothing to update to. Note that the vscode extension calls out to the `cmake-format` command with as a subprocess. You can update the `cmake-format` binary through `pip` (or however you installed in the first place) and it will continue to work with the existing vscode extension. 

I'm closing this issue but feel free to reply if you need to discuss further.
