### ISSUE TITLE
possible to always force kwargs on new line?

### ISSUE THREAD

**Issue by svenevs** [cheshirekow/cmake_format#93]
Easiest to show by example

`test.cmake`

```cmake
# too short, keeps them on one line
target_sources(my-target PUBLIC one.hpp PRIVATE one.cpp)
# make it long enough, does what i'm looking for
target_sources(my-target PUBLIC one.hpp two.hpp three.hpp four.hpp PRIVATE one.cpp two.cpp three.cpp four.cpp)
```

`test-config.py`

```py
dangle_parens = True
additional_commands = {
  "target_sources": {
    "kwargs": {
      "PUBLIC": "+",
      "PRIVATE": "+"
    }
  }
}
always_wrap = ["target_sources"]
```

Execution: `cmake-format -c test-config.py test.cmake`

```cmake
# too short, keeps them on one line
target_sources(
  my-target
  PUBLIC one.hpp
  PRIVATE one.cpp
)
# make it long enough, does what i'm looking for
target_sources(
  my-target
  PUBLIC
    one.hpp
    two.hpp
    three.hpp
    four.hpp
  PRIVATE
    one.cpp
    two.cpp
    three.cpp
    four.cpp
)
```

I tried playing around with the `algorithm_order`, but in general I don't want to globally change the algorithm order, I just want to signal a way to basically `always_wrap_kwargs` or something.  So the desired output for the short one would be

```cmake
target_sources(
  my-target
  PUBLIC
    one.hpp
  PRIVATE
    one.cpp
)
```

Am I missing a setting that enables this?

**Comment by cheshirekow** [comment]
Um... I think this can be done with with setting the `algorithm_order` on a per-command basis, which is either a feature I recently added or is still in progress... I can't remember where I left off with that. Lemme poke around a bit and get back to you.

**Comment by svenevs** [comment]
Hehe no worries. I can definitely live without this one... especially if it's hard to implement (ends don't justify the means)

**Comment by cheshirekow** [comment]
This was mentioned in another thread but since I'm not sure if I'll get to this for the next release I'll mention it here too: one workaround is to add an empty comment where you want to force a wrap. For instance with your example config, try this:
```
target_sources(
  my-target
  PUBLIC #
    one.hpp
  PRIVATE #
    one.cpp
)
```

**Comment by cheshirekow** [comment]
As of version `0.6.0`:
```.py
layout_passes = {
    "KwargGroupNode": [(0, True)]
}
```
Produces:
```.cmake
target_sources(
  my-target
  PUBLIC
    one.hpp
  PRIVATE
    one.cpp)
```


Note that we don't have a specification for the new `target_sources` command yet so you'll need to add one to your config:
```
additional_commands = {
    "target_sources": {
        "pargs": 1,
        "kwargs": {
            "PUBLIC": "*",
            "PRIVATE": "*"
        }
    }
}
```
I'm going to close this issue, but if you would like to discuss further please feel free to continue to do so here.

**Comment by svenevs** [comment]
Thanks! I think I'll have a little free time this weekend, do you seek `target_sources` definitions?

**Comment by cheshirekow** [comment]
That's ok. It's a simple command I'll add it in the next push 😉.

**Comment by sergeyklay** [comment]
For those who have no idea how to provide [this](https://github.com/cheshirekow/cmake_format/issues/93#issuecomment-543385374) in yaml:
```yml
layout_passes:
  KwargGroupNode:
    - !!python/tuple
      - 0
      - true
```
